// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: daemon.proto

package daemon

import (
	runc "github.com/cedana/cedana/pkg/api/plugins/runc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DumpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string       `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Stream  bool         `protobuf:"varint,2,opt,name=Stream,proto3" json:"Stream,omitempty"`
	Details *DumpDetails `protobuf:"bytes,3,opt,name=Details,proto3" json:"Details,omitempty"`
}

func (x *DumpReq) Reset() {
	*x = DumpReq{}
	mi := &file_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpReq) ProtoMessage() {}

func (x *DumpReq) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpReq.ProtoReflect.Descriptor instead.
func (*DumpReq) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *DumpReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DumpReq) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *DumpReq) GetDetails() *DumpDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type DumpResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *DumpResp) Reset() {
	*x = DumpResp{}
	mi := &file_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpResp) ProtoMessage() {}

func (x *DumpResp) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpResp.ProtoReflect.Descriptor instead.
func (*DumpResp) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *DumpResp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DumpResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DumpDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	// Types that are assignable to Opts:
	//
	//	*DumpDetails_PID
	//	*DumpDetails_Runc
	Opts isDumpDetails_Opts `protobuf_oneof:"Opts"`
}

func (x *DumpDetails) Reset() {
	*x = DumpDetails{}
	mi := &file_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpDetails) ProtoMessage() {}

func (x *DumpDetails) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpDetails.ProtoReflect.Descriptor instead.
func (*DumpDetails) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *DumpDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (m *DumpDetails) GetOpts() isDumpDetails_Opts {
	if m != nil {
		return m.Opts
	}
	return nil
}

func (x *DumpDetails) GetPID() uint32 {
	if x, ok := x.GetOpts().(*DumpDetails_PID); ok {
		return x.PID
	}
	return 0
}

func (x *DumpDetails) GetRunc() *runc.DumpOpts {
	if x, ok := x.GetOpts().(*DumpDetails_Runc); ok {
		return x.Runc
	}
	return nil
}

type isDumpDetails_Opts interface {
	isDumpDetails_Opts()
}

type DumpDetails_PID struct {
	PID uint32 `protobuf:"varint,2,opt,name=PID,proto3,oneof"`
}

type DumpDetails_Runc struct {
	Runc *runc.DumpOpts `protobuf:"bytes,3,opt,name=Runc,proto3,oneof"`
}

func (*DumpDetails_PID) isDumpDetails_Opts() {}

func (*DumpDetails_Runc) isDumpDetails_Opts() {}

type RestoreReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string          `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Stream  bool            `protobuf:"varint,2,opt,name=Stream,proto3" json:"Stream,omitempty"`
	Details *RestoreDetails `protobuf:"bytes,3,opt,name=Details,proto3" json:"Details,omitempty"`
}

func (x *RestoreReq) Reset() {
	*x = RestoreReq{}
	mi := &file_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreReq) ProtoMessage() {}

func (x *RestoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreReq.ProtoReflect.Descriptor instead.
func (*RestoreReq) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *RestoreReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RestoreReq) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *RestoreReq) GetDetails() *RestoreDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type RestoreResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *RestoreResp) Reset() {
	*x = RestoreResp{}
	mi := &file_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResp) ProtoMessage() {}

func (x *RestoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResp.ProtoReflect.Descriptor instead.
func (*RestoreResp) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestoreDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	// Types that are assignable to Opts:
	//
	//	*RestoreDetails_PID
	//	*RestoreDetails_Runc
	Opts isRestoreDetails_Opts `protobuf_oneof:"Opts"`
}

func (x *RestoreDetails) Reset() {
	*x = RestoreDetails{}
	mi := &file_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreDetails) ProtoMessage() {}

func (x *RestoreDetails) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreDetails.ProtoReflect.Descriptor instead.
func (*RestoreDetails) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (m *RestoreDetails) GetOpts() isRestoreDetails_Opts {
	if m != nil {
		return m.Opts
	}
	return nil
}

func (x *RestoreDetails) GetPID() uint32 {
	if x, ok := x.GetOpts().(*RestoreDetails_PID); ok {
		return x.PID
	}
	return 0
}

func (x *RestoreDetails) GetRunc() *runc.RestoreOpts {
	if x, ok := x.GetOpts().(*RestoreDetails_Runc); ok {
		return x.Runc
	}
	return nil
}

type isRestoreDetails_Opts interface {
	isRestoreDetails_Opts()
}

type RestoreDetails_PID struct {
	PID uint32 `protobuf:"varint,2,opt,name=PID,proto3,oneof"`
}

type RestoreDetails_Runc struct {
	Runc *runc.RestoreOpts `protobuf:"bytes,3,opt,name=Runc,proto3,oneof"`
}

func (*RestoreDetails_PID) isRestoreDetails_Opts() {}

func (*RestoreDetails_Runc) isRestoreDetails_Opts() {}

var File_daemon_proto protoreflect.FileDescriptor

var file_daemon_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x63, 0x65, 0x64, 0x61, 0x6e, 0x61, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x1a, 0x12, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x72, 0x75, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6b, 0x0a, 0x07, 0x44, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x34, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x65, 0x64, 0x61,
	0x6e, 0x61, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x75, 0x6d, 0x70, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x38,
	0x0a, 0x08, 0x44, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x72, 0x0a, 0x0b, 0x44, 0x75, 0x6d, 0x70,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x03, 0x50,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x03, 0x50, 0x49, 0x44, 0x12,
	0x33, 0x0a, 0x04, 0x52, 0x75, 0x6e, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x63, 0x65, 0x64, 0x61, 0x6e, 0x61, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x72,
	0x75, 0x6e, 0x63, 0x2e, 0x44, 0x75, 0x6d, 0x70, 0x4f, 0x70, 0x74, 0x73, 0x48, 0x00, 0x52, 0x04,
	0x52, 0x75, 0x6e, 0x63, 0x42, 0x06, 0x0a, 0x04, 0x4f, 0x70, 0x74, 0x73, 0x22, 0x71, 0x0a, 0x0a,
	0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x37, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x6e, 0x61,
	0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22,
	0x27, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x78, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x03, 0x50,
	0x49, 0x44, 0x12, 0x36, 0x0a, 0x04, 0x52, 0x75, 0x6e, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x6e, 0x61, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x73, 0x2e, 0x72, 0x75, 0x6e, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4f, 0x70,
	0x74, 0x73, 0x48, 0x00, 0x52, 0x04, 0x52, 0x75, 0x6e, 0x63, 0x42, 0x06, 0x0a, 0x04, 0x4f, 0x70,
	0x74, 0x73, 0x32, 0x87, 0x01, 0x0a, 0x06, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x39, 0x0a,
	0x04, 0x44, 0x75, 0x6d, 0x70, 0x12, 0x16, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x6e, 0x61, 0x2e, 0x64,
	0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e,
	0x63, 0x65, 0x64, 0x61, 0x6e, 0x61, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x75,
	0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x6e, 0x61, 0x2e, 0x64, 0x61, 0x65,
	0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x63, 0x65, 0x64, 0x61, 0x6e, 0x61, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x52,
	0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_daemon_proto_rawDescOnce sync.Once
	file_daemon_proto_rawDescData = file_daemon_proto_rawDesc
)

func file_daemon_proto_rawDescGZIP() []byte {
	file_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_daemon_proto_rawDescData)
	})
	return file_daemon_proto_rawDescData
}

var file_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_daemon_proto_goTypes = []any{
	(*DumpReq)(nil),          // 0: cedana.daemon.DumpReq
	(*DumpResp)(nil),         // 1: cedana.daemon.DumpResp
	(*DumpDetails)(nil),      // 2: cedana.daemon.DumpDetails
	(*RestoreReq)(nil),       // 3: cedana.daemon.RestoreReq
	(*RestoreResp)(nil),      // 4: cedana.daemon.RestoreResp
	(*RestoreDetails)(nil),   // 5: cedana.daemon.RestoreDetails
	(*runc.DumpOpts)(nil),    // 6: cedana.plugins.runc.DumpOpts
	(*runc.RestoreOpts)(nil), // 7: cedana.plugins.runc.RestoreOpts
}
var file_daemon_proto_depIdxs = []int32{
	2, // 0: cedana.daemon.DumpReq.Details:type_name -> cedana.daemon.DumpDetails
	6, // 1: cedana.daemon.DumpDetails.Runc:type_name -> cedana.plugins.runc.DumpOpts
	5, // 2: cedana.daemon.RestoreReq.Details:type_name -> cedana.daemon.RestoreDetails
	7, // 3: cedana.daemon.RestoreDetails.Runc:type_name -> cedana.plugins.runc.RestoreOpts
	0, // 4: cedana.daemon.Daemon.Dump:input_type -> cedana.daemon.DumpReq
	3, // 5: cedana.daemon.Daemon.Restore:input_type -> cedana.daemon.RestoreReq
	1, // 6: cedana.daemon.Daemon.Dump:output_type -> cedana.daemon.DumpResp
	4, // 7: cedana.daemon.Daemon.Restore:output_type -> cedana.daemon.RestoreResp
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_daemon_proto_init() }
func file_daemon_proto_init() {
	if File_daemon_proto != nil {
		return
	}
	file_daemon_proto_msgTypes[2].OneofWrappers = []any{
		(*DumpDetails_PID)(nil),
		(*DumpDetails_Runc)(nil),
	}
	file_daemon_proto_msgTypes[5].OneofWrappers = []any{
		(*RestoreDetails_PID)(nil),
		(*RestoreDetails_Runc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_daemon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_proto_depIdxs,
		MessageInfos:      file_daemon_proto_msgTypes,
	}.Build()
	File_daemon_proto = out.File
	file_daemon_proto_rawDesc = nil
	file_daemon_proto_goTypes = nil
	file_daemon_proto_depIdxs = nil
}
