// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sql

import (
	"time"
)

type Checkpoint struct {
	ID   string
	Jid  string
	Path string
	Time time.Time
	Size int64
}

type GpuController struct {
	ID          string
	Address     string
	Pid         int64
	Attachedpid int64
	Freezetype  int64
}

type Host struct {
	ID            string
	Mac           string
	Hostname      string
	Os            string
	Platform      string
	Kernelversion string
	Kernelarch    string
	Cpuphysicalid string
	Cpuvendorid   string
	Cpufamily     string
	Cpucount      int64
	Memtotal      int64
}

type Job struct {
	Jid        string
	Type       string
	Gpuenabled int64
	Log        string
	Details    []byte
	Pid        int64
	Cmdline    string
	Starttime  time.Time
	Workingdir string
	Status     string
	Isrunning  int64
	Hostid     string
	Uids       string
	Gids       string
	Groups     string
}
