// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package task

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FlagEnum int32

const (
	FlagEnum_JOB_STARTUP_FAILED FlagEnum = 0
	FlagEnum_JOB_KILLED         FlagEnum = 1
	FlagEnum_JOB_IDLE           FlagEnum = 2
	FlagEnum_JOB_RUNNING        FlagEnum = 3
	FlagEnum_JOB_PENDING        FlagEnum = 4
	FlagEnum_JOB_SETUP_FAILED   FlagEnum = 5
	FlagEnum_JOB_DONE           FlagEnum = 6
)

var FlagEnum_name = map[int32]string{
	0: "JOB_STARTUP_FAILED",
	1: "JOB_KILLED",
	2: "JOB_IDLE",
	3: "JOB_RUNNING",
	4: "JOB_PENDING",
	5: "JOB_SETUP_FAILED",
	6: "JOB_DONE",
}

var FlagEnum_value = map[string]int32{
	"JOB_STARTUP_FAILED": 0,
	"JOB_KILLED":         1,
	"JOB_IDLE":           2,
	"JOB_RUNNING":        3,
	"JOB_PENDING":        4,
	"JOB_SETUP_FAILED":   5,
	"JOB_DONE":           6,
}

func (x FlagEnum) String() string {
	return proto.EnumName(FlagEnum_name, int32(x))
}

func (FlagEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

type CheckpointState int32

const (
	CheckpointState_CHECKPOINTED      CheckpointState = 0
	CheckpointState_CHECKPOINT_FAILED CheckpointState = 1
	CheckpointState_RESTORED          CheckpointState = 2
	CheckpointState_RESTORE_FAILED    CheckpointState = 3
)

var CheckpointState_name = map[int32]string{
	0: "CHECKPOINTED",
	1: "CHECKPOINT_FAILED",
	2: "RESTORED",
	3: "RESTORE_FAILED",
}

var CheckpointState_value = map[string]int32{
	"CHECKPOINTED":      0,
	"CHECKPOINT_FAILED": 1,
	"RESTORED":          2,
	"RESTORE_FAILED":    3,
}

func (x CheckpointState) String() string {
	return proto.EnumName(CheckpointState_name, int32(x))
}

func (CheckpointState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

type DumpArgs_DumpType int32

const (
	DumpArgs_SELF_SERVE DumpArgs_DumpType = 0
	DumpArgs_MARKET     DumpArgs_DumpType = 1
)

var DumpArgs_DumpType_name = map[int32]string{
	0: "SELF_SERVE",
	1: "MARKET",
}

var DumpArgs_DumpType_value = map[string]int32{
	"SELF_SERVE": 0,
	"MARKET":     1,
}

func (x DumpArgs_DumpType) String() string {
	return proto.EnumName(DumpArgs_DumpType_name, int32(x))
}

func (DumpArgs_DumpType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0, 0}
}

type RestoreArgs_RestoreType int32

const (
	RestoreArgs_LOCAL  RestoreArgs_RestoreType = 0
	RestoreArgs_REMOTE RestoreArgs_RestoreType = 1
)

var RestoreArgs_RestoreType_name = map[int32]string{
	0: "LOCAL",
	1: "REMOTE",
}

var RestoreArgs_RestoreType_value = map[string]int32{
	"LOCAL":  0,
	"REMOTE": 1,
}

func (x RestoreArgs_RestoreType) String() string {
	return proto.EnumName(RestoreArgs_RestoreType_name, int32(x))
}

func (RestoreArgs_RestoreType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2, 0}
}

type ProcessState_ContainerRuntimeOpts int32

const (
	ProcessState_CONTAINERD ProcessState_ContainerRuntimeOpts = 0
	ProcessState_RUNC       ProcessState_ContainerRuntimeOpts = 1
)

var ProcessState_ContainerRuntimeOpts_name = map[int32]string{
	0: "CONTAINERD",
	1: "RUNC",
}

var ProcessState_ContainerRuntimeOpts_value = map[string]int32{
	"CONTAINERD": 0,
	"RUNC":       1,
}

func (x ProcessState_ContainerRuntimeOpts) String() string {
	return proto.EnumName(ProcessState_ContainerRuntimeOpts_name, int32(x))
}

func (ProcessState_ContainerRuntimeOpts) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{8, 0}
}

type CheckpointReason_CheckpointReasonEnum int32

const (
	CheckpointReason_INSTANCE_TERMINATION CheckpointReason_CheckpointReasonEnum = 0
	CheckpointReason_JOB_TERMINATION      CheckpointReason_CheckpointReasonEnum = 1
	CheckpointReason_HEARTBEAT            CheckpointReason_CheckpointReasonEnum = 2
)

var CheckpointReason_CheckpointReasonEnum_name = map[int32]string{
	0: "INSTANCE_TERMINATION",
	1: "JOB_TERMINATION",
	2: "HEARTBEAT",
}

var CheckpointReason_CheckpointReasonEnum_value = map[string]int32{
	"INSTANCE_TERMINATION": 0,
	"JOB_TERMINATION":      1,
	"HEARTBEAT":            2,
}

func (x CheckpointReason_CheckpointReasonEnum) String() string {
	return proto.EnumName(CheckpointReason_CheckpointReasonEnum_name, int32(x))
}

func (CheckpointReason_CheckpointReasonEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{16, 0}
}

type DumpArgs struct {
	PID                  int32             `protobuf:"varint,1,opt,name=PID,proto3" json:"PID,omitempty"`
	Dir                  string            `protobuf:"bytes,2,opt,name=Dir,proto3" json:"Dir,omitempty"`
	Type                 DumpArgs_DumpType `protobuf:"varint,3,opt,name=Type,proto3,enum=cedana.services.task.DumpArgs_DumpType" json:"Type,omitempty"`
	JobID                string            `protobuf:"bytes,4,opt,name=JobID,proto3" json:"JobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DumpArgs) Reset()         { *m = DumpArgs{} }
func (m *DumpArgs) String() string { return proto.CompactTextString(m) }
func (*DumpArgs) ProtoMessage()    {}
func (*DumpArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *DumpArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpArgs.Unmarshal(m, b)
}
func (m *DumpArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpArgs.Marshal(b, m, deterministic)
}
func (m *DumpArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpArgs.Merge(m, src)
}
func (m *DumpArgs) XXX_Size() int {
	return xxx_messageInfo_DumpArgs.Size(m)
}
func (m *DumpArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpArgs.DiscardUnknown(m)
}

var xxx_messageInfo_DumpArgs proto.InternalMessageInfo

func (m *DumpArgs) GetPID() int32 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *DumpArgs) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *DumpArgs) GetType() DumpArgs_DumpType {
	if m != nil {
		return m.Type
	}
	return DumpArgs_SELF_SERVE
}

func (m *DumpArgs) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

type DumpResp struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpResp) Reset()         { *m = DumpResp{} }
func (m *DumpResp) String() string { return proto.CompactTextString(m) }
func (*DumpResp) ProtoMessage()    {}
func (*DumpResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *DumpResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpResp.Unmarshal(m, b)
}
func (m *DumpResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpResp.Marshal(b, m, deterministic)
}
func (m *DumpResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpResp.Merge(m, src)
}
func (m *DumpResp) XXX_Size() int {
	return xxx_messageInfo_DumpResp.Size(m)
}
func (m *DumpResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpResp.DiscardUnknown(m)
}

var xxx_messageInfo_DumpResp proto.InternalMessageInfo

func (m *DumpResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RestoreArgs struct {
	Type                 RestoreArgs_RestoreType `protobuf:"varint,1,opt,name=Type,proto3,enum=cedana.services.task.RestoreArgs_RestoreType" json:"Type,omitempty"`
	CheckpointId         string                  `protobuf:"bytes,2,opt,name=CheckpointId,proto3" json:"CheckpointId,omitempty"`
	CheckpointPath       string                  `protobuf:"bytes,3,opt,name=CheckpointPath,proto3" json:"CheckpointPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RestoreArgs) Reset()         { *m = RestoreArgs{} }
func (m *RestoreArgs) String() string { return proto.CompactTextString(m) }
func (*RestoreArgs) ProtoMessage()    {}
func (*RestoreArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *RestoreArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreArgs.Unmarshal(m, b)
}
func (m *RestoreArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreArgs.Marshal(b, m, deterministic)
}
func (m *RestoreArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreArgs.Merge(m, src)
}
func (m *RestoreArgs) XXX_Size() int {
	return xxx_messageInfo_RestoreArgs.Size(m)
}
func (m *RestoreArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreArgs.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreArgs proto.InternalMessageInfo

func (m *RestoreArgs) GetType() RestoreArgs_RestoreType {
	if m != nil {
		return m.Type
	}
	return RestoreArgs_LOCAL
}

func (m *RestoreArgs) GetCheckpointId() string {
	if m != nil {
		return m.CheckpointId
	}
	return ""
}

func (m *RestoreArgs) GetCheckpointPath() string {
	if m != nil {
		return m.CheckpointPath
	}
	return ""
}

type RestoreResp struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	NewPID               int32    `protobuf:"varint,2,opt,name=NewPID,proto3" json:"NewPID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreResp) Reset()         { *m = RestoreResp{} }
func (m *RestoreResp) String() string { return proto.CompactTextString(m) }
func (*RestoreResp) ProtoMessage()    {}
func (*RestoreResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{3}
}

func (m *RestoreResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreResp.Unmarshal(m, b)
}
func (m *RestoreResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreResp.Marshal(b, m, deterministic)
}
func (m *RestoreResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreResp.Merge(m, src)
}
func (m *RestoreResp) XXX_Size() int {
	return xxx_messageInfo_RestoreResp.Size(m)
}
func (m *RestoreResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreResp.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreResp proto.InternalMessageInfo

func (m *RestoreResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RestoreResp) GetNewPID() int32 {
	if m != nil {
		return m.NewPID
	}
	return 0
}

type StartTaskArgs struct {
	Task                 string   `protobuf:"bytes,1,opt,name=Task,proto3" json:"Task,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartTaskArgs) Reset()         { *m = StartTaskArgs{} }
func (m *StartTaskArgs) String() string { return proto.CompactTextString(m) }
func (*StartTaskArgs) ProtoMessage()    {}
func (*StartTaskArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{4}
}

func (m *StartTaskArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTaskArgs.Unmarshal(m, b)
}
func (m *StartTaskArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTaskArgs.Marshal(b, m, deterministic)
}
func (m *StartTaskArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTaskArgs.Merge(m, src)
}
func (m *StartTaskArgs) XXX_Size() int {
	return xxx_messageInfo_StartTaskArgs.Size(m)
}
func (m *StartTaskArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTaskArgs.DiscardUnknown(m)
}

var xxx_messageInfo_StartTaskArgs proto.InternalMessageInfo

func (m *StartTaskArgs) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

func (m *StartTaskArgs) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StartTaskResp struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	PID                  int32    `protobuf:"varint,2,opt,name=PID,proto3" json:"PID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartTaskResp) Reset()         { *m = StartTaskResp{} }
func (m *StartTaskResp) String() string { return proto.CompactTextString(m) }
func (*StartTaskResp) ProtoMessage()    {}
func (*StartTaskResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{5}
}

func (m *StartTaskResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTaskResp.Unmarshal(m, b)
}
func (m *StartTaskResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTaskResp.Marshal(b, m, deterministic)
}
func (m *StartTaskResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTaskResp.Merge(m, src)
}
func (m *StartTaskResp) XXX_Size() int {
	return xxx_messageInfo_StartTaskResp.Size(m)
}
func (m *StartTaskResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTaskResp.DiscardUnknown(m)
}

var xxx_messageInfo_StartTaskResp proto.InternalMessageInfo

func (m *StartTaskResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *StartTaskResp) GetPID() int32 {
	if m != nil {
		return m.PID
	}
	return 0
}

// Log Streaming args
type LogStreamingArgs struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	Level                string   `protobuf:"bytes,3,opt,name=Level,proto3" json:"Level,omitempty"`
	Msg                  string   `protobuf:"bytes,4,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogStreamingArgs) Reset()         { *m = LogStreamingArgs{} }
func (m *LogStreamingArgs) String() string { return proto.CompactTextString(m) }
func (*LogStreamingArgs) ProtoMessage()    {}
func (*LogStreamingArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{6}
}

func (m *LogStreamingArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogStreamingArgs.Unmarshal(m, b)
}
func (m *LogStreamingArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogStreamingArgs.Marshal(b, m, deterministic)
}
func (m *LogStreamingArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogStreamingArgs.Merge(m, src)
}
func (m *LogStreamingArgs) XXX_Size() int {
	return xxx_messageInfo_LogStreamingArgs.Size(m)
}
func (m *LogStreamingArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_LogStreamingArgs.DiscardUnknown(m)
}

var xxx_messageInfo_LogStreamingArgs proto.InternalMessageInfo

func (m *LogStreamingArgs) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *LogStreamingArgs) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *LogStreamingArgs) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *LogStreamingArgs) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LogStreamingResp struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogStreamingResp) Reset()         { *m = LogStreamingResp{} }
func (m *LogStreamingResp) String() string { return proto.CompactTextString(m) }
func (*LogStreamingResp) ProtoMessage()    {}
func (*LogStreamingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{7}
}

func (m *LogStreamingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogStreamingResp.Unmarshal(m, b)
}
func (m *LogStreamingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogStreamingResp.Marshal(b, m, deterministic)
}
func (m *LogStreamingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogStreamingResp.Merge(m, src)
}
func (m *LogStreamingResp) XXX_Size() int {
	return xxx_messageInfo_LogStreamingResp.Size(m)
}
func (m *LogStreamingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogStreamingResp.DiscardUnknown(m)
}

var xxx_messageInfo_LogStreamingResp proto.InternalMessageInfo

func (m *LogStreamingResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ProcessState struct {
	PID                  int32                             `protobuf:"varint,1,opt,name=PID,proto3" json:"PID,omitempty"`
	Task                 string                            `protobuf:"bytes,2,opt,name=Task,proto3" json:"Task,omitempty"`
	ContainerRuntime     ProcessState_ContainerRuntimeOpts `protobuf:"varint,3,opt,name=ContainerRuntime,proto3,enum=cedana.services.task.ProcessState_ContainerRuntimeOpts" json:"ContainerRuntime,omitempty"`
	ContainerId          string                            `protobuf:"bytes,4,opt,name=ContainerId,proto3" json:"ContainerId,omitempty"`
	StartedAt            string                            `protobuf:"bytes,5,opt,name=StartedAt,proto3" json:"StartedAt,omitempty"`
	ProcessInfo          *ProcessInfo                      `protobuf:"bytes,6,opt,name=ProcessInfo,proto3" json:"ProcessInfo,omitempty"`
	CheckpointPath       string                            `protobuf:"bytes,7,opt,name=CheckpointPath,proto3" json:"CheckpointPath,omitempty"`
	CheckpointState      CheckpointState                   `protobuf:"varint,8,opt,name=CheckpointState,proto3,enum=cedana.services.task.CheckpointState" json:"CheckpointState,omitempty"`
	Flag                 FlagEnum                          `protobuf:"varint,9,opt,name=Flag,proto3,enum=cedana.services.task.FlagEnum" json:"Flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ProcessState) Reset()         { *m = ProcessState{} }
func (m *ProcessState) String() string { return proto.CompactTextString(m) }
func (*ProcessState) ProtoMessage()    {}
func (*ProcessState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{8}
}

func (m *ProcessState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessState.Unmarshal(m, b)
}
func (m *ProcessState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessState.Marshal(b, m, deterministic)
}
func (m *ProcessState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessState.Merge(m, src)
}
func (m *ProcessState) XXX_Size() int {
	return xxx_messageInfo_ProcessState.Size(m)
}
func (m *ProcessState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessState.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessState proto.InternalMessageInfo

func (m *ProcessState) GetPID() int32 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *ProcessState) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

func (m *ProcessState) GetContainerRuntime() ProcessState_ContainerRuntimeOpts {
	if m != nil {
		return m.ContainerRuntime
	}
	return ProcessState_CONTAINERD
}

func (m *ProcessState) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *ProcessState) GetStartedAt() string {
	if m != nil {
		return m.StartedAt
	}
	return ""
}

func (m *ProcessState) GetProcessInfo() *ProcessInfo {
	if m != nil {
		return m.ProcessInfo
	}
	return nil
}

func (m *ProcessState) GetCheckpointPath() string {
	if m != nil {
		return m.CheckpointPath
	}
	return ""
}

func (m *ProcessState) GetCheckpointState() CheckpointState {
	if m != nil {
		return m.CheckpointState
	}
	return CheckpointState_CHECKPOINTED
}

func (m *ProcessState) GetFlag() FlagEnum {
	if m != nil {
		return m.Flag
	}
	return FlagEnum_JOB_STARTUP_FAILED
}

type ClientInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	Platform             string   `protobuf:"bytes,3,opt,name=Platform,proto3" json:"Platform,omitempty"`
	OS                   string   `protobuf:"bytes,4,opt,name=OS,proto3" json:"OS,omitempty"`
	Uptime               uint64   `protobuf:"varint,5,opt,name=Uptime,proto3" json:"Uptime,omitempty"`
	RemainingMemory      uint64   `protobuf:"varint,6,opt,name=RemainingMemory,proto3" json:"RemainingMemory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{9}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClientInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *ClientInfo) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *ClientInfo) GetOS() string {
	if m != nil {
		return m.OS
	}
	return ""
}

func (m *ClientInfo) GetUptime() uint64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *ClientInfo) GetRemainingMemory() uint64 {
	if m != nil {
		return m.RemainingMemory
	}
	return 0
}

type ProcessInfo struct {
	PID                     int32             `protobuf:"varint,1,opt,name=PID,proto3" json:"PID,omitempty"`
	AttachedToHardwareAccel bool              `protobuf:"varint,2,opt,name=AttachedToHardwareAccel,proto3" json:"AttachedToHardwareAccel,omitempty"`
	OpenFds                 []*OpenFilesStat  `protobuf:"bytes,3,rep,name=OpenFds,proto3" json:"OpenFds,omitempty"`
	OpenWriteOnlyFilePaths  []string          `protobuf:"bytes,4,rep,name=OpenWriteOnlyFilePaths,proto3" json:"OpenWriteOnlyFilePaths,omitempty"`
	OpenConnections         []*ConnectionStat `protobuf:"bytes,5,rep,name=OpenConnections,proto3" json:"OpenConnections,omitempty"`
	MemoryPercent           float32           `protobuf:"fixed32,6,opt,name=MemoryPercent,proto3" json:"MemoryPercent,omitempty"`
	IsRunning               bool              `protobuf:"varint,7,opt,name=IsRunning,proto3" json:"IsRunning,omitempty"`
	Status                  string            `protobuf:"bytes,8,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}          `json:"-"`
	XXX_unrecognized        []byte            `json:"-"`
	XXX_sizecache           int32             `json:"-"`
}

func (m *ProcessInfo) Reset()         { *m = ProcessInfo{} }
func (m *ProcessInfo) String() string { return proto.CompactTextString(m) }
func (*ProcessInfo) ProtoMessage()    {}
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{10}
}

func (m *ProcessInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessInfo.Unmarshal(m, b)
}
func (m *ProcessInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessInfo.Marshal(b, m, deterministic)
}
func (m *ProcessInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessInfo.Merge(m, src)
}
func (m *ProcessInfo) XXX_Size() int {
	return xxx_messageInfo_ProcessInfo.Size(m)
}
func (m *ProcessInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessInfo proto.InternalMessageInfo

func (m *ProcessInfo) GetPID() int32 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *ProcessInfo) GetAttachedToHardwareAccel() bool {
	if m != nil {
		return m.AttachedToHardwareAccel
	}
	return false
}

func (m *ProcessInfo) GetOpenFds() []*OpenFilesStat {
	if m != nil {
		return m.OpenFds
	}
	return nil
}

func (m *ProcessInfo) GetOpenWriteOnlyFilePaths() []string {
	if m != nil {
		return m.OpenWriteOnlyFilePaths
	}
	return nil
}

func (m *ProcessInfo) GetOpenConnections() []*ConnectionStat {
	if m != nil {
		return m.OpenConnections
	}
	return nil
}

func (m *ProcessInfo) GetMemoryPercent() float32 {
	if m != nil {
		return m.MemoryPercent
	}
	return 0
}

func (m *ProcessInfo) GetIsRunning() bool {
	if m != nil {
		return m.IsRunning
	}
	return false
}

func (m *ProcessInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type OpenFilesStat struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Fd                   uint64   `protobuf:"varint,2,opt,name=Fd,proto3" json:"Fd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenFilesStat) Reset()         { *m = OpenFilesStat{} }
func (m *OpenFilesStat) String() string { return proto.CompactTextString(m) }
func (*OpenFilesStat) ProtoMessage()    {}
func (*OpenFilesStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{11}
}

func (m *OpenFilesStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenFilesStat.Unmarshal(m, b)
}
func (m *OpenFilesStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenFilesStat.Marshal(b, m, deterministic)
}
func (m *OpenFilesStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenFilesStat.Merge(m, src)
}
func (m *OpenFilesStat) XXX_Size() int {
	return xxx_messageInfo_OpenFilesStat.Size(m)
}
func (m *OpenFilesStat) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenFilesStat.DiscardUnknown(m)
}

var xxx_messageInfo_OpenFilesStat proto.InternalMessageInfo

func (m *OpenFilesStat) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *OpenFilesStat) GetFd() uint64 {
	if m != nil {
		return m.Fd
	}
	return 0
}

type ConnectionStat struct {
	Fd                   uint32   `protobuf:"varint,1,opt,name=Fd,proto3" json:"Fd,omitempty"`
	Family               uint32   `protobuf:"varint,2,opt,name=Family,proto3" json:"Family,omitempty"`
	Type                 uint32   `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Laddr                *Addr    `protobuf:"bytes,4,opt,name=Laddr,proto3" json:"Laddr,omitempty"`
	Raddr                *Addr    `protobuf:"bytes,5,opt,name=Raddr,proto3" json:"Raddr,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
	Uids                 []int32  `protobuf:"varint,7,rep,packed,name=Uids,proto3" json:"Uids,omitempty"`
	PID                  int32    `protobuf:"varint,8,opt,name=PID,proto3" json:"PID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionStat) Reset()         { *m = ConnectionStat{} }
func (m *ConnectionStat) String() string { return proto.CompactTextString(m) }
func (*ConnectionStat) ProtoMessage()    {}
func (*ConnectionStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{12}
}

func (m *ConnectionStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionStat.Unmarshal(m, b)
}
func (m *ConnectionStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionStat.Marshal(b, m, deterministic)
}
func (m *ConnectionStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionStat.Merge(m, src)
}
func (m *ConnectionStat) XXX_Size() int {
	return xxx_messageInfo_ConnectionStat.Size(m)
}
func (m *ConnectionStat) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionStat.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionStat proto.InternalMessageInfo

func (m *ConnectionStat) GetFd() uint32 {
	if m != nil {
		return m.Fd
	}
	return 0
}

func (m *ConnectionStat) GetFamily() uint32 {
	if m != nil {
		return m.Family
	}
	return 0
}

func (m *ConnectionStat) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ConnectionStat) GetLaddr() *Addr {
	if m != nil {
		return m.Laddr
	}
	return nil
}

func (m *ConnectionStat) GetRaddr() *Addr {
	if m != nil {
		return m.Raddr
	}
	return nil
}

func (m *ConnectionStat) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ConnectionStat) GetUids() []int32 {
	if m != nil {
		return m.Uids
	}
	return nil
}

func (m *ConnectionStat) GetPID() int32 {
	if m != nil {
		return m.PID
	}
	return 0
}

type Addr struct {
	IP                   string   `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Addr) Reset()         { *m = Addr{} }
func (m *Addr) String() string { return proto.CompactTextString(m) }
func (*Addr) ProtoMessage()    {}
func (*Addr) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{13}
}

func (m *Addr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Addr.Unmarshal(m, b)
}
func (m *Addr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Addr.Marshal(b, m, deterministic)
}
func (m *Addr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Addr.Merge(m, src)
}
func (m *Addr) XXX_Size() int {
	return xxx_messageInfo_Addr.Size(m)
}
func (m *Addr) XXX_DiscardUnknown() {
	xxx_messageInfo_Addr.DiscardUnknown(m)
}

var xxx_messageInfo_Addr proto.InternalMessageInfo

func (m *Addr) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *Addr) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type ClientStateStreamingResp struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientStateStreamingResp) Reset()         { *m = ClientStateStreamingResp{} }
func (m *ClientStateStreamingResp) String() string { return proto.CompactTextString(m) }
func (*ClientStateStreamingResp) ProtoMessage()    {}
func (*ClientStateStreamingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{14}
}

func (m *ClientStateStreamingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientStateStreamingResp.Unmarshal(m, b)
}
func (m *ClientStateStreamingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientStateStreamingResp.Marshal(b, m, deterministic)
}
func (m *ClientStateStreamingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientStateStreamingResp.Merge(m, src)
}
func (m *ClientStateStreamingResp) XXX_Size() int {
	return xxx_messageInfo_ClientStateStreamingResp.Size(m)
}
func (m *ClientStateStreamingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientStateStreamingResp.DiscardUnknown(m)
}

var xxx_messageInfo_ClientStateStreamingResp proto.InternalMessageInfo

func (m *ClientStateStreamingResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type MetaStateStreamingArgs struct {
	Event                *ProviderEvent    `protobuf:"bytes,1,opt,name=Event,proto3" json:"Event,omitempty"`
	CheckpointReason     *CheckpointReason `protobuf:"bytes,2,opt,name=CheckpointReason,proto3" json:"CheckpointReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MetaStateStreamingArgs) Reset()         { *m = MetaStateStreamingArgs{} }
func (m *MetaStateStreamingArgs) String() string { return proto.CompactTextString(m) }
func (*MetaStateStreamingArgs) ProtoMessage()    {}
func (*MetaStateStreamingArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{15}
}

func (m *MetaStateStreamingArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaStateStreamingArgs.Unmarshal(m, b)
}
func (m *MetaStateStreamingArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaStateStreamingArgs.Marshal(b, m, deterministic)
}
func (m *MetaStateStreamingArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaStateStreamingArgs.Merge(m, src)
}
func (m *MetaStateStreamingArgs) XXX_Size() int {
	return xxx_messageInfo_MetaStateStreamingArgs.Size(m)
}
func (m *MetaStateStreamingArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaStateStreamingArgs.DiscardUnknown(m)
}

var xxx_messageInfo_MetaStateStreamingArgs proto.InternalMessageInfo

func (m *MetaStateStreamingArgs) GetEvent() *ProviderEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *MetaStateStreamingArgs) GetCheckpointReason() *CheckpointReason {
	if m != nil {
		return m.CheckpointReason
	}
	return nil
}

type CheckpointReason struct {
	Reason               CheckpointReason_CheckpointReasonEnum `protobuf:"varint,1,opt,name=Reason,proto3,enum=cedana.services.task.CheckpointReason_CheckpointReasonEnum" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *CheckpointReason) Reset()         { *m = CheckpointReason{} }
func (m *CheckpointReason) String() string { return proto.CompactTextString(m) }
func (*CheckpointReason) ProtoMessage()    {}
func (*CheckpointReason) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{16}
}

func (m *CheckpointReason) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckpointReason.Unmarshal(m, b)
}
func (m *CheckpointReason) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckpointReason.Marshal(b, m, deterministic)
}
func (m *CheckpointReason) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckpointReason.Merge(m, src)
}
func (m *CheckpointReason) XXX_Size() int {
	return xxx_messageInfo_CheckpointReason.Size(m)
}
func (m *CheckpointReason) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckpointReason.DiscardUnknown(m)
}

var xxx_messageInfo_CheckpointReason proto.InternalMessageInfo

func (m *CheckpointReason) GetReason() CheckpointReason_CheckpointReasonEnum {
	if m != nil {
		return m.Reason
	}
	return CheckpointReason_INSTANCE_TERMINATION
}

type ProviderEvent struct {
	InstanceID           string   `protobuf:"bytes,1,opt,name=InstanceID,proto3" json:"InstanceID,omitempty"`
	FaultCode            string   `protobuf:"bytes,2,opt,name=FaultCode,proto3" json:"FaultCode,omitempty"`
	MarkedForTermination bool     `protobuf:"varint,3,opt,name=MarkedForTermination,proto3" json:"MarkedForTermination,omitempty"`
	TerminationTime      int64    `protobuf:"varint,4,opt,name=TerminationTime,proto3" json:"TerminationTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderEvent) Reset()         { *m = ProviderEvent{} }
func (m *ProviderEvent) String() string { return proto.CompactTextString(m) }
func (*ProviderEvent) ProtoMessage()    {}
func (*ProviderEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{17}
}

func (m *ProviderEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderEvent.Unmarshal(m, b)
}
func (m *ProviderEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderEvent.Marshal(b, m, deterministic)
}
func (m *ProviderEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderEvent.Merge(m, src)
}
func (m *ProviderEvent) XXX_Size() int {
	return xxx_messageInfo_ProviderEvent.Size(m)
}
func (m *ProviderEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderEvent proto.InternalMessageInfo

func (m *ProviderEvent) GetInstanceID() string {
	if m != nil {
		return m.InstanceID
	}
	return ""
}

func (m *ProviderEvent) GetFaultCode() string {
	if m != nil {
		return m.FaultCode
	}
	return ""
}

func (m *ProviderEvent) GetMarkedForTermination() bool {
	if m != nil {
		return m.MarkedForTermination
	}
	return false
}

func (m *ProviderEvent) GetTerminationTime() int64 {
	if m != nil {
		return m.TerminationTime
	}
	return 0
}

type MetaStateStreamingResp struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaStateStreamingResp) Reset()         { *m = MetaStateStreamingResp{} }
func (m *MetaStateStreamingResp) String() string { return proto.CompactTextString(m) }
func (*MetaStateStreamingResp) ProtoMessage()    {}
func (*MetaStateStreamingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{18}
}

func (m *MetaStateStreamingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaStateStreamingResp.Unmarshal(m, b)
}
func (m *MetaStateStreamingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaStateStreamingResp.Marshal(b, m, deterministic)
}
func (m *MetaStateStreamingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaStateStreamingResp.Merge(m, src)
}
func (m *MetaStateStreamingResp) XXX_Size() int {
	return xxx_messageInfo_MetaStateStreamingResp.Size(m)
}
func (m *MetaStateStreamingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaStateStreamingResp.DiscardUnknown(m)
}

var xxx_messageInfo_MetaStateStreamingResp proto.InternalMessageInfo

func (m *MetaStateStreamingResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ContainerDumpArgs struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=ContainerId,proto3" json:"ContainerId,omitempty"`
	Ref                  string   `protobuf:"bytes,2,opt,name=Ref,proto3" json:"Ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerDumpArgs) Reset()         { *m = ContainerDumpArgs{} }
func (m *ContainerDumpArgs) String() string { return proto.CompactTextString(m) }
func (*ContainerDumpArgs) ProtoMessage()    {}
func (*ContainerDumpArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{19}
}

func (m *ContainerDumpArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerDumpArgs.Unmarshal(m, b)
}
func (m *ContainerDumpArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerDumpArgs.Marshal(b, m, deterministic)
}
func (m *ContainerDumpArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerDumpArgs.Merge(m, src)
}
func (m *ContainerDumpArgs) XXX_Size() int {
	return xxx_messageInfo_ContainerDumpArgs.Size(m)
}
func (m *ContainerDumpArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerDumpArgs.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerDumpArgs proto.InternalMessageInfo

func (m *ContainerDumpArgs) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *ContainerDumpArgs) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

type ContainerDumpResp struct {
	CheckpointPath       string   `protobuf:"bytes,1,opt,name=CheckpointPath,proto3" json:"CheckpointPath,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerDumpResp) Reset()         { *m = ContainerDumpResp{} }
func (m *ContainerDumpResp) String() string { return proto.CompactTextString(m) }
func (*ContainerDumpResp) ProtoMessage()    {}
func (*ContainerDumpResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{20}
}

func (m *ContainerDumpResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerDumpResp.Unmarshal(m, b)
}
func (m *ContainerDumpResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerDumpResp.Marshal(b, m, deterministic)
}
func (m *ContainerDumpResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerDumpResp.Merge(m, src)
}
func (m *ContainerDumpResp) XXX_Size() int {
	return xxx_messageInfo_ContainerDumpResp.Size(m)
}
func (m *ContainerDumpResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerDumpResp.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerDumpResp proto.InternalMessageInfo

func (m *ContainerDumpResp) GetCheckpointPath() string {
	if m != nil {
		return m.CheckpointPath
	}
	return ""
}

func (m *ContainerDumpResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ContainerRestoreArgs struct {
	ImgPath              string   `protobuf:"bytes,1,opt,name=ImgPath,proto3" json:"ImgPath,omitempty"`
	ContainerId          string   `protobuf:"bytes,2,opt,name=ContainerId,proto3" json:"ContainerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerRestoreArgs) Reset()         { *m = ContainerRestoreArgs{} }
func (m *ContainerRestoreArgs) String() string { return proto.CompactTextString(m) }
func (*ContainerRestoreArgs) ProtoMessage()    {}
func (*ContainerRestoreArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{21}
}

func (m *ContainerRestoreArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerRestoreArgs.Unmarshal(m, b)
}
func (m *ContainerRestoreArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerRestoreArgs.Marshal(b, m, deterministic)
}
func (m *ContainerRestoreArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerRestoreArgs.Merge(m, src)
}
func (m *ContainerRestoreArgs) XXX_Size() int {
	return xxx_messageInfo_ContainerRestoreArgs.Size(m)
}
func (m *ContainerRestoreArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerRestoreArgs.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerRestoreArgs proto.InternalMessageInfo

func (m *ContainerRestoreArgs) GetImgPath() string {
	if m != nil {
		return m.ImgPath
	}
	return ""
}

func (m *ContainerRestoreArgs) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type ContainerRestoreResp struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerRestoreResp) Reset()         { *m = ContainerRestoreResp{} }
func (m *ContainerRestoreResp) String() string { return proto.CompactTextString(m) }
func (*ContainerRestoreResp) ProtoMessage()    {}
func (*ContainerRestoreResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{22}
}

func (m *ContainerRestoreResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerRestoreResp.Unmarshal(m, b)
}
func (m *ContainerRestoreResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerRestoreResp.Marshal(b, m, deterministic)
}
func (m *ContainerRestoreResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerRestoreResp.Merge(m, src)
}
func (m *ContainerRestoreResp) XXX_Size() int {
	return xxx_messageInfo_ContainerRestoreResp.Size(m)
}
func (m *ContainerRestoreResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerRestoreResp.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerRestoreResp proto.InternalMessageInfo

func (m *ContainerRestoreResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RuncDumpArgs struct {
	Root                 string    `protobuf:"bytes,1,opt,name=Root,proto3" json:"Root,omitempty"`
	CheckpointPath       string    `protobuf:"bytes,2,opt,name=CheckpointPath,proto3" json:"CheckpointPath,omitempty"`
	ContainerId          string    `protobuf:"bytes,3,opt,name=ContainerId,proto3" json:"ContainerId,omitempty"`
	CriuOpts             *CriuOpts `protobuf:"bytes,4,opt,name=CriuOpts,proto3" json:"CriuOpts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RuncDumpArgs) Reset()         { *m = RuncDumpArgs{} }
func (m *RuncDumpArgs) String() string { return proto.CompactTextString(m) }
func (*RuncDumpArgs) ProtoMessage()    {}
func (*RuncDumpArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{23}
}

func (m *RuncDumpArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuncDumpArgs.Unmarshal(m, b)
}
func (m *RuncDumpArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuncDumpArgs.Marshal(b, m, deterministic)
}
func (m *RuncDumpArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuncDumpArgs.Merge(m, src)
}
func (m *RuncDumpArgs) XXX_Size() int {
	return xxx_messageInfo_RuncDumpArgs.Size(m)
}
func (m *RuncDumpArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_RuncDumpArgs.DiscardUnknown(m)
}

var xxx_messageInfo_RuncDumpArgs proto.InternalMessageInfo

func (m *RuncDumpArgs) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *RuncDumpArgs) GetCheckpointPath() string {
	if m != nil {
		return m.CheckpointPath
	}
	return ""
}

func (m *RuncDumpArgs) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *RuncDumpArgs) GetCriuOpts() *CriuOpts {
	if m != nil {
		return m.CriuOpts
	}
	return nil
}

type RuncDumpResp struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuncDumpResp) Reset()         { *m = RuncDumpResp{} }
func (m *RuncDumpResp) String() string { return proto.CompactTextString(m) }
func (*RuncDumpResp) ProtoMessage()    {}
func (*RuncDumpResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{24}
}

func (m *RuncDumpResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuncDumpResp.Unmarshal(m, b)
}
func (m *RuncDumpResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuncDumpResp.Marshal(b, m, deterministic)
}
func (m *RuncDumpResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuncDumpResp.Merge(m, src)
}
func (m *RuncDumpResp) XXX_Size() int {
	return xxx_messageInfo_RuncDumpResp.Size(m)
}
func (m *RuncDumpResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RuncDumpResp.DiscardUnknown(m)
}

var xxx_messageInfo_RuncDumpResp proto.InternalMessageInfo

func (m *RuncDumpResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CriuOpts struct {
	ImagesDirectory         string   `protobuf:"bytes,1,opt,name=ImagesDirectory,proto3" json:"ImagesDirectory,omitempty"`
	WorkDirectory           string   `protobuf:"bytes,2,opt,name=WorkDirectory,proto3" json:"WorkDirectory,omitempty"`
	ParentImage             string   `protobuf:"bytes,3,opt,name=ParentImage,proto3" json:"ParentImage,omitempty"`
	LeaveRunning            bool     `protobuf:"varint,4,opt,name=LeaveRunning,proto3" json:"LeaveRunning,omitempty"`
	TcpEstablished          bool     `protobuf:"varint,5,opt,name=TcpEstablished,proto3" json:"TcpEstablished,omitempty"`
	ExternalUnixConnections bool     `protobuf:"varint,6,opt,name=ExternalUnixConnections,proto3" json:"ExternalUnixConnections,omitempty"`
	ShellJob                bool     `protobuf:"varint,7,opt,name=ShellJob,proto3" json:"ShellJob,omitempty"`
	FileLocks               bool     `protobuf:"varint,8,opt,name=FileLocks,proto3" json:"FileLocks,omitempty"`
	PreDump                 bool     `protobuf:"varint,9,opt,name=PreDump,proto3" json:"PreDump,omitempty"`
	EmptyNs                 uint32   `protobuf:"varint,12,opt,name=EmptyNs,proto3" json:"EmptyNs,omitempty"`
	AutoDedup               bool     `protobuf:"varint,13,opt,name=AutoDedup,proto3" json:"AutoDedup,omitempty"`
	LazyPages               bool     `protobuf:"varint,14,opt,name=LazyPages,proto3" json:"LazyPages,omitempty"`
	StatusFd                int32    `protobuf:"varint,15,opt,name=StatusFd,proto3" json:"StatusFd,omitempty"`
	LsmProfile              string   `protobuf:"bytes,16,opt,name=LsmProfile,proto3" json:"LsmProfile,omitempty"`
	LsmMountContext         string   `protobuf:"bytes,17,opt,name=LsmMountContext,proto3" json:"LsmMountContext,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *CriuOpts) Reset()         { *m = CriuOpts{} }
func (m *CriuOpts) String() string { return proto.CompactTextString(m) }
func (*CriuOpts) ProtoMessage()    {}
func (*CriuOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{25}
}

func (m *CriuOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriuOpts.Unmarshal(m, b)
}
func (m *CriuOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriuOpts.Marshal(b, m, deterministic)
}
func (m *CriuOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriuOpts.Merge(m, src)
}
func (m *CriuOpts) XXX_Size() int {
	return xxx_messageInfo_CriuOpts.Size(m)
}
func (m *CriuOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_CriuOpts.DiscardUnknown(m)
}

var xxx_messageInfo_CriuOpts proto.InternalMessageInfo

func (m *CriuOpts) GetImagesDirectory() string {
	if m != nil {
		return m.ImagesDirectory
	}
	return ""
}

func (m *CriuOpts) GetWorkDirectory() string {
	if m != nil {
		return m.WorkDirectory
	}
	return ""
}

func (m *CriuOpts) GetParentImage() string {
	if m != nil {
		return m.ParentImage
	}
	return ""
}

func (m *CriuOpts) GetLeaveRunning() bool {
	if m != nil {
		return m.LeaveRunning
	}
	return false
}

func (m *CriuOpts) GetTcpEstablished() bool {
	if m != nil {
		return m.TcpEstablished
	}
	return false
}

func (m *CriuOpts) GetExternalUnixConnections() bool {
	if m != nil {
		return m.ExternalUnixConnections
	}
	return false
}

func (m *CriuOpts) GetShellJob() bool {
	if m != nil {
		return m.ShellJob
	}
	return false
}

func (m *CriuOpts) GetFileLocks() bool {
	if m != nil {
		return m.FileLocks
	}
	return false
}

func (m *CriuOpts) GetPreDump() bool {
	if m != nil {
		return m.PreDump
	}
	return false
}

func (m *CriuOpts) GetEmptyNs() uint32 {
	if m != nil {
		return m.EmptyNs
	}
	return 0
}

func (m *CriuOpts) GetAutoDedup() bool {
	if m != nil {
		return m.AutoDedup
	}
	return false
}

func (m *CriuOpts) GetLazyPages() bool {
	if m != nil {
		return m.LazyPages
	}
	return false
}

func (m *CriuOpts) GetStatusFd() int32 {
	if m != nil {
		return m.StatusFd
	}
	return 0
}

func (m *CriuOpts) GetLsmProfile() string {
	if m != nil {
		return m.LsmProfile
	}
	return ""
}

func (m *CriuOpts) GetLsmMountContext() string {
	if m != nil {
		return m.LsmMountContext
	}
	return ""
}

type RuncRestoreArgs struct {
	ContainerId          string    `protobuf:"bytes,1,opt,name=ContainerId,proto3" json:"ContainerId,omitempty"`
	ImagePath            string    `protobuf:"bytes,2,opt,name=ImagePath,proto3" json:"ImagePath,omitempty"`
	Opts                 *RuncOpts `protobuf:"bytes,4,opt,name=Opts,proto3" json:"Opts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RuncRestoreArgs) Reset()         { *m = RuncRestoreArgs{} }
func (m *RuncRestoreArgs) String() string { return proto.CompactTextString(m) }
func (*RuncRestoreArgs) ProtoMessage()    {}
func (*RuncRestoreArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{26}
}

func (m *RuncRestoreArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuncRestoreArgs.Unmarshal(m, b)
}
func (m *RuncRestoreArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuncRestoreArgs.Marshal(b, m, deterministic)
}
func (m *RuncRestoreArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuncRestoreArgs.Merge(m, src)
}
func (m *RuncRestoreArgs) XXX_Size() int {
	return xxx_messageInfo_RuncRestoreArgs.Size(m)
}
func (m *RuncRestoreArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_RuncRestoreArgs.DiscardUnknown(m)
}

var xxx_messageInfo_RuncRestoreArgs proto.InternalMessageInfo

func (m *RuncRestoreArgs) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *RuncRestoreArgs) GetImagePath() string {
	if m != nil {
		return m.ImagePath
	}
	return ""
}

func (m *RuncRestoreArgs) GetOpts() *RuncOpts {
	if m != nil {
		return m.Opts
	}
	return nil
}

type RuncOpts struct {
	Root                 string   `protobuf:"bytes,1,opt,name=Root,proto3" json:"Root,omitempty"`
	ContainerId          string   `protobuf:"bytes,2,opt,name=ContainerId,proto3" json:"ContainerId,omitempty"`
	Bundle               string   `protobuf:"bytes,3,opt,name=Bundle,proto3" json:"Bundle,omitempty"`
	SystemdCgroup        bool     `protobuf:"varint,4,opt,name=SystemdCgroup,proto3" json:"SystemdCgroup,omitempty"`
	NoPivot              bool     `protobuf:"varint,5,opt,name=NoPivot,proto3" json:"NoPivot,omitempty"`
	NoMountFallback      bool     `protobuf:"varint,6,opt,name=NoMountFallback,proto3" json:"NoMountFallback,omitempty"`
	NoNewKeyring         bool     `protobuf:"varint,7,opt,name=NoNewKeyring,proto3" json:"NoNewKeyring,omitempty"`
	Rootless             string   `protobuf:"bytes,8,opt,name=Rootless,proto3" json:"Rootless,omitempty"`
	NoSubreaper          bool     `protobuf:"varint,9,opt,name=NoSubreaper,proto3" json:"NoSubreaper,omitempty"`
	Keep                 bool     `protobuf:"varint,10,opt,name=Keep,proto3" json:"Keep,omitempty"`
	ConsoleSocket        string   `protobuf:"bytes,11,opt,name=ConsoleSocket,proto3" json:"ConsoleSocket,omitempty"`
	Detatch              bool     `protobuf:"varint,12,opt,name=Detatch,proto3" json:"Detatch,omitempty"`
	PidFile              string   `protobuf:"bytes,13,opt,name=PidFile,proto3" json:"PidFile,omitempty"`
	PreserveFds          int32    `protobuf:"varint,14,opt,name=PreserveFds,proto3" json:"PreserveFds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuncOpts) Reset()         { *m = RuncOpts{} }
func (m *RuncOpts) String() string { return proto.CompactTextString(m) }
func (*RuncOpts) ProtoMessage()    {}
func (*RuncOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{27}
}

func (m *RuncOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuncOpts.Unmarshal(m, b)
}
func (m *RuncOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuncOpts.Marshal(b, m, deterministic)
}
func (m *RuncOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuncOpts.Merge(m, src)
}
func (m *RuncOpts) XXX_Size() int {
	return xxx_messageInfo_RuncOpts.Size(m)
}
func (m *RuncOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_RuncOpts.DiscardUnknown(m)
}

var xxx_messageInfo_RuncOpts proto.InternalMessageInfo

func (m *RuncOpts) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *RuncOpts) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *RuncOpts) GetBundle() string {
	if m != nil {
		return m.Bundle
	}
	return ""
}

func (m *RuncOpts) GetSystemdCgroup() bool {
	if m != nil {
		return m.SystemdCgroup
	}
	return false
}

func (m *RuncOpts) GetNoPivot() bool {
	if m != nil {
		return m.NoPivot
	}
	return false
}

func (m *RuncOpts) GetNoMountFallback() bool {
	if m != nil {
		return m.NoMountFallback
	}
	return false
}

func (m *RuncOpts) GetNoNewKeyring() bool {
	if m != nil {
		return m.NoNewKeyring
	}
	return false
}

func (m *RuncOpts) GetRootless() string {
	if m != nil {
		return m.Rootless
	}
	return ""
}

func (m *RuncOpts) GetNoSubreaper() bool {
	if m != nil {
		return m.NoSubreaper
	}
	return false
}

func (m *RuncOpts) GetKeep() bool {
	if m != nil {
		return m.Keep
	}
	return false
}

func (m *RuncOpts) GetConsoleSocket() string {
	if m != nil {
		return m.ConsoleSocket
	}
	return ""
}

func (m *RuncOpts) GetDetatch() bool {
	if m != nil {
		return m.Detatch
	}
	return false
}

func (m *RuncOpts) GetPidFile() string {
	if m != nil {
		return m.PidFile
	}
	return ""
}

func (m *RuncOpts) GetPreserveFds() int32 {
	if m != nil {
		return m.PreserveFds
	}
	return 0
}

type RuncRestoreResp struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuncRestoreResp) Reset()         { *m = RuncRestoreResp{} }
func (m *RuncRestoreResp) String() string { return proto.CompactTextString(m) }
func (*RuncRestoreResp) ProtoMessage()    {}
func (*RuncRestoreResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{28}
}

func (m *RuncRestoreResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuncRestoreResp.Unmarshal(m, b)
}
func (m *RuncRestoreResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuncRestoreResp.Marshal(b, m, deterministic)
}
func (m *RuncRestoreResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuncRestoreResp.Merge(m, src)
}
func (m *RuncRestoreResp) XXX_Size() int {
	return xxx_messageInfo_RuncRestoreResp.Size(m)
}
func (m *RuncRestoreResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RuncRestoreResp.DiscardUnknown(m)
}

var xxx_messageInfo_RuncRestoreResp proto.InternalMessageInfo

func (m *RuncRestoreResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("cedana.services.task.FlagEnum", FlagEnum_name, FlagEnum_value)
	proto.RegisterEnum("cedana.services.task.CheckpointState", CheckpointState_name, CheckpointState_value)
	proto.RegisterEnum("cedana.services.task.DumpArgs_DumpType", DumpArgs_DumpType_name, DumpArgs_DumpType_value)
	proto.RegisterEnum("cedana.services.task.RestoreArgs_RestoreType", RestoreArgs_RestoreType_name, RestoreArgs_RestoreType_value)
	proto.RegisterEnum("cedana.services.task.ProcessState_ContainerRuntimeOpts", ProcessState_ContainerRuntimeOpts_name, ProcessState_ContainerRuntimeOpts_value)
	proto.RegisterEnum("cedana.services.task.CheckpointReason_CheckpointReasonEnum", CheckpointReason_CheckpointReasonEnum_name, CheckpointReason_CheckpointReasonEnum_value)
	proto.RegisterType((*DumpArgs)(nil), "cedana.services.task.DumpArgs")
	proto.RegisterType((*DumpResp)(nil), "cedana.services.task.DumpResp")
	proto.RegisterType((*RestoreArgs)(nil), "cedana.services.task.RestoreArgs")
	proto.RegisterType((*RestoreResp)(nil), "cedana.services.task.RestoreResp")
	proto.RegisterType((*StartTaskArgs)(nil), "cedana.services.task.StartTaskArgs")
	proto.RegisterType((*StartTaskResp)(nil), "cedana.services.task.StartTaskResp")
	proto.RegisterType((*LogStreamingArgs)(nil), "cedana.services.task.LogStreamingArgs")
	proto.RegisterType((*LogStreamingResp)(nil), "cedana.services.task.LogStreamingResp")
	proto.RegisterType((*ProcessState)(nil), "cedana.services.task.ProcessState")
	proto.RegisterType((*ClientInfo)(nil), "cedana.services.task.ClientInfo")
	proto.RegisterType((*ProcessInfo)(nil), "cedana.services.task.ProcessInfo")
	proto.RegisterType((*OpenFilesStat)(nil), "cedana.services.task.OpenFilesStat")
	proto.RegisterType((*ConnectionStat)(nil), "cedana.services.task.ConnectionStat")
	proto.RegisterType((*Addr)(nil), "cedana.services.task.Addr")
	proto.RegisterType((*ClientStateStreamingResp)(nil), "cedana.services.task.ClientStateStreamingResp")
	proto.RegisterType((*MetaStateStreamingArgs)(nil), "cedana.services.task.MetaStateStreamingArgs")
	proto.RegisterType((*CheckpointReason)(nil), "cedana.services.task.CheckpointReason")
	proto.RegisterType((*ProviderEvent)(nil), "cedana.services.task.ProviderEvent")
	proto.RegisterType((*MetaStateStreamingResp)(nil), "cedana.services.task.MetaStateStreamingResp")
	proto.RegisterType((*ContainerDumpArgs)(nil), "cedana.services.task.ContainerDumpArgs")
	proto.RegisterType((*ContainerDumpResp)(nil), "cedana.services.task.ContainerDumpResp")
	proto.RegisterType((*ContainerRestoreArgs)(nil), "cedana.services.task.ContainerRestoreArgs")
	proto.RegisterType((*ContainerRestoreResp)(nil), "cedana.services.task.ContainerRestoreResp")
	proto.RegisterType((*RuncDumpArgs)(nil), "cedana.services.task.RuncDumpArgs")
	proto.RegisterType((*RuncDumpResp)(nil), "cedana.services.task.RuncDumpResp")
	proto.RegisterType((*CriuOpts)(nil), "cedana.services.task.CriuOpts")
	proto.RegisterType((*RuncRestoreArgs)(nil), "cedana.services.task.RuncRestoreArgs")
	proto.RegisterType((*RuncOpts)(nil), "cedana.services.task.RuncOpts")
	proto.RegisterType((*RuncRestoreResp)(nil), "cedana.services.task.RuncRestoreResp")
}

func init() {
	proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff)
}

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 2045 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x58, 0xdd, 0x6e, 0xdb, 0xca,
	0xf1, 0x0f, 0x25, 0xd9, 0x96, 0x47, 0xb6, 0xac, 0xec, 0xdf, 0xff, 0x94, 0x30, 0x8a, 0xc0, 0x87,
	0x27, 0x27, 0x31, 0x8c, 0xd4, 0x09, 0x1c, 0xa0, 0xa7, 0x6d, 0xd0, 0x0b, 0x45, 0xa2, 0x4e, 0x94,
	0xc8, 0x94, 0xba, 0x92, 0x7b, 0x80, 0xb6, 0x40, 0x40, 0x93, 0x6b, 0x99, 0x35, 0xc5, 0x15, 0xc8,
	0x95, 0x13, 0xf7, 0xbe, 0x7d, 0x80, 0x3e, 0x44, 0x3f, 0xd0, 0xdb, 0xde, 0xf6, 0xa6, 0x37, 0x7d,
	0x9b, 0x3e, 0x41, 0x0b, 0x14, 0x33, 0xfc, 0x10, 0x25, 0x51, 0xb6, 0xaf, 0xb4, 0x33, 0x3b, 0xdf,
	0xfb, 0xdb, 0x99, 0x15, 0x01, 0x94, 0x1d, 0x5d, 0x9f, 0x4c, 0x43, 0xa9, 0x24, 0xdb, 0x77, 0x84,
	0x6b, 0x07, 0xf6, 0x49, 0x24, 0xc2, 0x1b, 0xcf, 0x11, 0xd1, 0x09, 0xee, 0x19, 0x7f, 0xd5, 0xa0,
	0xda, 0x9e, 0x4d, 0xa6, 0xcd, 0x70, 0x1c, 0xb1, 0x06, 0x94, 0x07, 0xdd, 0xb6, 0xae, 0x1d, 0x6a,
	0x47, 0x1b, 0x1c, 0x97, 0xc8, 0x69, 0x7b, 0xa1, 0x5e, 0x3a, 0xd4, 0x8e, 0xb6, 0x39, 0x2e, 0xd9,
	0x5b, 0xa8, 0x8c, 0x6e, 0xa7, 0x42, 0x2f, 0x1f, 0x6a, 0x47, 0xf5, 0xd3, 0x17, 0x27, 0x45, 0x56,
	0x4f, 0x52, 0x8b, 0xb4, 0x40, 0x71, 0x4e, 0x4a, 0x6c, 0x1f, 0x36, 0x3e, 0xc8, 0x8b, 0x6e, 0x5b,
	0xaf, 0x90, 0xc1, 0x98, 0x30, 0x9e, 0xc7, 0x21, 0x90, 0x44, 0x1d, 0x60, 0x68, 0xf6, 0x3a, 0x9f,
	0x86, 0x26, 0xff, 0xa5, 0xd9, 0x78, 0xc4, 0x00, 0x36, 0xcf, 0x9a, 0xfc, 0xa3, 0x39, 0x6a, 0x68,
	0xc6, 0x61, 0x2c, 0xc7, 0x45, 0x34, 0x45, 0x4b, 0x66, 0x18, 0xca, 0x90, 0x82, 0xdd, 0xe6, 0x31,
	0x61, 0xfc, 0x53, 0x83, 0x1a, 0x17, 0x91, 0x92, 0xa1, 0xa0, 0x84, 0x9a, 0x49, 0xb0, 0x1a, 0x05,
	0xfb, 0xa3, 0xe2, 0x60, 0x73, 0x0a, 0xe9, 0x3a, 0x17, 0xb2, 0x01, 0x3b, 0xad, 0x2b, 0xe1, 0x5c,
	0x4f, 0xa5, 0x17, 0xa8, 0xae, 0x9b, 0x94, 0x62, 0x81, 0xc7, 0x9e, 0x43, 0x7d, 0x4e, 0x0f, 0x6c,
	0x75, 0x45, 0xd5, 0xd9, 0xe6, 0x4b, 0x5c, 0xe3, 0x59, 0x16, 0x1d, 0x99, 0xde, 0x86, 0x8d, 0x5e,
	0xbf, 0xd5, 0xec, 0xc5, 0x69, 0x72, 0xf3, 0xac, 0x3f, 0x32, 0x1b, 0x9a, 0xf1, 0x36, 0x93, 0x5a,
	0x9f, 0x29, 0x7b, 0x02, 0x9b, 0x96, 0xf8, 0x8c, 0xa7, 0x55, 0xa2, 0xd3, 0x4a, 0x28, 0xe3, 0x0d,
	0xec, 0x0e, 0x95, 0x1d, 0xaa, 0x91, 0x1d, 0x5d, 0x53, 0x09, 0x18, 0x54, 0x70, 0x9d, 0x68, 0xd3,
	0x9a, 0xd5, 0xa1, 0x94, 0x65, 0x52, 0xea, 0xba, 0xc6, 0xb7, 0x39, 0xa5, 0x3b, 0x7c, 0x26, 0xf0,
	0x28, 0x65, 0xf0, 0x30, 0xa6, 0xd0, 0xe8, 0xc9, 0xf1, 0x50, 0x85, 0xc2, 0x9e, 0x78, 0xc1, 0x98,
	0x1c, 0xfe, 0x10, 0xb6, 0x47, 0xde, 0x44, 0x44, 0xca, 0x9e, 0x4c, 0x13, 0xfd, 0x39, 0x03, 0xe3,
	0x1e, 0xca, 0x59, 0xe8, 0x88, 0xc4, 0x7d, 0x42, 0xa1, 0xc7, 0x9e, 0xb8, 0x11, 0x7e, 0x52, 0xb9,
	0x98, 0x40, 0x8f, 0x67, 0xd1, 0x38, 0x41, 0x0b, 0x2e, 0x8d, 0xe3, 0x45, 0x8f, 0x14, 0x2d, 0xda,
	0x54, 0xb6, 0x9a, 0x45, 0x89, 0xbb, 0x84, 0x32, 0xfe, 0x5b, 0x86, 0x9d, 0x41, 0x28, 0x1d, 0x11,
	0x45, 0xc8, 0x11, 0x05, 0xf8, 0x4e, 0xab, 0x53, 0xca, 0x55, 0xc7, 0x81, 0x46, 0x4b, 0x06, 0xca,
	0xf6, 0x02, 0x11, 0xf2, 0x59, 0xa0, 0xbc, 0x49, 0x8a, 0xf6, 0x6f, 0x8b, 0x01, 0x94, 0xf7, 0x71,
	0xb2, 0xac, 0xda, 0x9f, 0xaa, 0x88, 0xaf, 0x18, 0x64, 0x87, 0x50, 0xcb, 0x78, 0x5d, 0x37, 0xc9,
	0x30, 0xcf, 0xc2, 0x3a, 0xd2, 0xa1, 0x08, 0xb7, 0xa9, 0xf4, 0x8d, 0xb8, 0x8e, 0x19, 0x83, 0xb5,
	0xa0, 0x96, 0xb8, 0xed, 0x06, 0x97, 0x52, 0xdf, 0x3c, 0xd4, 0x8e, 0x6a, 0xa7, 0x5f, 0xdd, 0x19,
	0x1f, 0x0a, 0xf2, 0xbc, 0x56, 0x01, 0x6e, 0xb7, 0x8a, 0x70, 0xcb, 0xfa, 0xb0, 0x37, 0xe7, 0x50,
	0x9a, 0x7a, 0x95, 0x0a, 0xf2, 0x4d, 0xb1, 0x43, 0x67, 0x51, 0x98, 0x2f, 0x6b, 0xb3, 0x53, 0xa8,
	0x74, 0x7c, 0x7b, 0xac, 0x6f, 0x93, 0x95, 0xa7, 0xc5, 0x56, 0x50, 0xc2, 0x0c, 0x66, 0x13, 0x4e,
	0xb2, 0xc6, 0x6b, 0xd8, 0x2f, 0xaa, 0x2d, 0x76, 0x8c, 0x56, 0xdf, 0x1a, 0x35, 0xbb, 0x96, 0xc9,
	0xdb, 0x8d, 0x47, 0xac, 0x0a, 0x15, 0x7e, 0x6e, 0xb5, 0x1a, 0x9a, 0xf1, 0x27, 0x0d, 0xa0, 0xe5,
	0x7b, 0x22, 0x50, 0x94, 0x6d, 0x8c, 0x7a, 0x2d, 0x45, 0x3d, 0x3b, 0x80, 0xea, 0x7b, 0x19, 0xa9,
	0xc0, 0x9e, 0xa4, 0x60, 0xcc, 0x68, 0xdc, 0x1b, 0xf8, 0xb6, 0xba, 0x94, 0xe1, 0x24, 0x41, 0x64,
	0x46, 0xa3, 0x9d, 0xfe, 0x30, 0x39, 0xb1, 0x52, 0x7f, 0x88, 0xf0, 0x3b, 0x9f, 0x12, 0x4a, 0xf0,
	0x94, 0x2a, 0x3c, 0xa1, 0xd8, 0x11, 0xec, 0x71, 0x31, 0xb1, 0xbd, 0xc0, 0x0b, 0xc6, 0x67, 0x62,
	0x22, 0xc3, 0x5b, 0x3a, 0xa6, 0x0a, 0x5f, 0x66, 0x1b, 0xff, 0x29, 0x2d, 0x9c, 0x66, 0x01, 0x4e,
	0x7f, 0x02, 0x3f, 0x68, 0x2a, 0x65, 0x3b, 0x57, 0xc2, 0x1d, 0xc9, 0xf7, 0x76, 0xe8, 0x7e, 0xb6,
	0x43, 0xd1, 0x74, 0x1c, 0xe1, 0x53, 0xe8, 0x55, 0xbe, 0x6e, 0x9b, 0xfd, 0x1c, 0xb6, 0xfa, 0x53,
	0x11, 0x74, 0xdc, 0x48, 0x2f, 0x1f, 0x96, 0x8f, 0x6a, 0xa7, 0x5f, 0x17, 0x57, 0x9b, 0x84, 0x3c,
	0x5f, 0x10, 0x8c, 0x79, 0xaa, 0xc3, 0x7e, 0x0c, 0x4f, 0x70, 0xf9, 0x7d, 0xe8, 0x29, 0xd1, 0x0f,
	0xfc, 0x5b, 0x14, 0x41, 0x4c, 0x44, 0x7a, 0xe5, 0xb0, 0x7c, 0xb4, 0xcd, 0xd7, 0xec, 0x32, 0x0b,
	0xf6, 0x70, 0xa7, 0x25, 0x83, 0x40, 0x38, 0xca, 0x93, 0x41, 0xa4, 0x6f, 0x90, 0xfb, 0x67, 0xc5,
	0xee, 0xe7, 0x82, 0xe4, 0x7f, 0x59, 0x99, 0x3d, 0x83, 0xdd, 0xb8, 0x58, 0x03, 0x11, 0x3a, 0x22,
	0x50, 0x54, 0xca, 0x12, 0x5f, 0x64, 0xe2, 0x9d, 0xe9, 0x46, 0x7c, 0x16, 0x60, 0x6d, 0x09, 0xcb,
	0x55, 0x3e, 0x67, 0xe4, 0xfa, 0x44, 0x75, 0xa1, 0x4f, 0xbc, 0x81, 0xdd, 0x85, 0xec, 0xb1, 0x2b,
	0xd0, 0x6d, 0x48, 0x7a, 0x26, 0xdd, 0x81, 0x3a, 0x94, 0x3a, 0x71, 0xcf, 0xac, 0xf0, 0x52, 0xc7,
	0x35, 0xfe, 0xad, 0x41, 0x7d, 0x31, 0xe8, 0x44, 0x04, 0x95, 0x76, 0x51, 0x04, 0xfd, 0x75, 0xec,
	0x89, 0xe7, 0xdf, 0x92, 0xda, 0x2e, 0x4f, 0x28, 0x6a, 0x3a, 0xe9, 0x08, 0xdd, 0x4d, 0xc6, 0xcc,
	0x6b, 0xd8, 0xe8, 0xd9, 0xae, 0x1b, 0x12, 0xae, 0x6a, 0xa7, 0x07, 0xc5, 0x55, 0x6a, 0xba, 0x6e,
	0xc8, 0x63, 0x41, 0xd4, 0xe0, 0xa4, 0xb1, 0x71, 0xbf, 0x06, 0x09, 0xe6, 0xf2, 0xdf, 0xcc, 0xe7,
	0x8f, 0xf1, 0x9c, 0x7b, 0x6e, 0xa4, 0x6f, 0x1d, 0x96, 0x8f, 0x36, 0x38, 0xad, 0x53, 0x08, 0x56,
	0xe7, 0xbd, 0xfe, 0x18, 0x2a, 0x68, 0x8c, 0xae, 0xd1, 0x20, 0xbb, 0x46, 0x03, 0x2a, 0x96, 0x0c,
	0x55, 0x92, 0x23, 0xad, 0x8d, 0x53, 0xd0, 0xe3, 0x8b, 0x47, 0xd7, 0xfd, 0x61, 0xdd, 0xfa, 0xcf,
	0x1a, 0x3c, 0x39, 0x13, 0xca, 0x5e, 0x54, 0xa1, 0x91, 0xf2, 0x53, 0xd8, 0x30, 0x6f, 0xf0, 0xd0,
	0x35, 0x4a, 0xf5, 0xeb, 0xb5, 0x6d, 0xee, 0xc6, 0x73, 0x45, 0x48, 0xa2, 0x3c, 0xd6, 0x60, 0x1c,
	0x1a, 0xf3, 0xe6, 0xc3, 0x85, 0x1d, 0xc9, 0x80, 0x22, 0xad, 0x9d, 0x3e, 0x5f, 0x03, 0xc4, 0x25,
	0x69, 0xbe, 0xa2, 0x6f, 0xfc, 0x43, 0x5b, 0x35, 0xca, 0x86, 0xb0, 0x99, 0x98, 0x8f, 0x1f, 0x1b,
	0x6f, 0x1f, 0x66, 0x7e, 0x85, 0x41, 0x1d, 0x2f, 0x31, 0x65, 0x8c, 0x60, 0xbf, 0x68, 0x9f, 0xe9,
	0xb0, 0xdf, 0xb5, 0x86, 0xa3, 0xa6, 0xd5, 0x32, 0x3f, 0x8d, 0x4c, 0x7e, 0xd6, 0xb5, 0x9a, 0xa3,
	0x6e, 0xdf, 0x6a, 0x3c, 0x62, 0xff, 0x07, 0x7b, 0x1f, 0xfa, 0xef, 0x16, 0x98, 0x1a, 0xdb, 0x85,
	0xed, 0xf7, 0x66, 0x93, 0x8f, 0xde, 0x99, 0xcd, 0x51, 0xa3, 0x64, 0xfc, 0x4d, 0x83, 0xdd, 0x85,
	0x62, 0xb1, 0xa7, 0x00, 0xdd, 0x20, 0x52, 0x76, 0xe0, 0x88, 0xa4, 0xef, 0x6c, 0xf3, 0x1c, 0x07,
	0xef, 0x55, 0xc7, 0x9e, 0xf9, 0xaa, 0x25, 0xdd, 0xb4, 0x57, 0xce, 0x19, 0xec, 0x14, 0xf6, 0xcf,
	0xec, 0xf0, 0x5a, 0xb8, 0x1d, 0x19, 0x8e, 0x44, 0x38, 0xf1, 0x02, 0x1b, 0xef, 0x04, 0xe1, 0xbb,
	0xca, 0x0b, 0xf7, 0xb0, 0x39, 0xe6, 0x48, 0x7c, 0x1f, 0x10, 0xf2, 0xcb, 0x7c, 0x99, 0x6d, 0xbc,
	0x2e, 0x82, 0xc5, 0x9d, 0x48, 0xfa, 0x0e, 0x1e, 0x67, 0x93, 0x22, 0x7b, 0xdb, 0x2e, 0x0d, 0x5c,
	0x6d, 0x75, 0xe0, 0x36, 0xa0, 0xcc, 0xc5, 0x65, 0xfa, 0xd6, 0xe5, 0xe2, 0xd2, 0xf8, 0xc5, 0x92,
	0x21, 0xf2, 0xba, 0x3a, 0x34, 0xb5, 0xc2, 0xa1, 0x99, 0xbd, 0xa1, 0x4a, 0xf9, 0x17, 0x2a, 0xcf,
	0x4f, 0xb1, 0xdc, 0x4b, 0x55, 0x87, 0xad, 0xee, 0x64, 0x9c, 0x33, 0x97, 0x92, 0xcb, 0x81, 0x97,
	0x56, 0x02, 0x37, 0x5e, 0xae, 0xda, 0xbc, 0xe3, 0x8d, 0xfc, 0x17, 0x0d, 0x76, 0xf8, 0x2c, 0x70,
	0xb2, 0xca, 0x30, 0xa8, 0x70, 0x29, 0x55, 0xda, 0xed, 0x70, 0x5d, 0x90, 0x64, 0xa9, 0x30, 0xc9,
	0xa5, 0xe0, 0xca, 0xab, 0x55, 0xfd, 0x19, 0x54, 0x5b, 0xa1, 0x37, 0xc3, 0x51, 0x9d, 0xf4, 0xb6,
	0x35, 0xe3, 0x3e, 0x95, 0xe2, 0x99, 0xbc, 0xf1, 0x6c, 0x1e, 0xe9, 0x1d, 0x09, 0xfd, 0xb1, 0x32,
	0x77, 0x81, 0xb8, 0xea, 0x4e, 0xec, 0xb1, 0x88, 0xda, 0x5e, 0x28, 0x1c, 0x85, 0x43, 0x37, 0x16,
	0x5e, 0x66, 0xe3, 0x44, 0xf9, 0x5e, 0x86, 0xd7, 0x73, 0xb9, 0x38, 0xc3, 0x45, 0x26, 0x26, 0x38,
	0xb0, 0x43, 0x7c, 0x42, 0xa0, 0x7a, 0x9a, 0x60, 0x8e, 0x85, 0x7f, 0x10, 0x7a, 0xc2, 0xbe, 0x11,
	0xe9, 0xd8, 0xa9, 0x10, 0xea, 0x17, 0x78, 0x58, 0xce, 0x91, 0x33, 0x35, 0x23, 0x65, 0x5f, 0xf8,
	0x5e, 0x74, 0x25, 0x5c, 0x6a, 0xda, 0x55, 0xbe, 0xc4, 0xc5, 0x31, 0x6f, 0x7e, 0x51, 0x22, 0x0c,
	0x6c, 0xff, 0x3c, 0xf0, 0xbe, 0xe4, 0xa7, 0xe7, 0x66, 0x3c, 0xe6, 0xd7, 0x6c, 0xe3, 0x83, 0x65,
	0x78, 0x25, 0x7c, 0xff, 0x83, 0xbc, 0x48, 0x06, 0x5f, 0x46, 0xd3, 0xed, 0xf5, 0x7c, 0xd1, 0x93,
	0xce, 0x75, 0x3c, 0xfa, 0xaa, 0x7c, 0xce, 0x40, 0xe4, 0x0d, 0x42, 0x81, 0x35, 0xa6, 0xe7, 0x58,
	0x95, 0xa7, 0x24, 0xee, 0x98, 0x93, 0xa9, 0xba, 0xb5, 0x22, 0x7d, 0x87, 0x9a, 0x7b, 0x4a, 0xa2,
	0xc5, 0xe6, 0x4c, 0xc9, 0xb6, 0x70, 0x67, 0x53, 0x7d, 0x37, 0xb6, 0x98, 0x31, 0x70, 0xb7, 0x67,
	0xff, 0xee, 0x76, 0x80, 0xf5, 0xd6, 0xeb, 0xf1, 0x6e, 0xc6, 0xa0, 0x48, 0xe9, 0x9e, 0x76, 0x5c,
	0x7d, 0x8f, 0xc6, 0x4b, 0x46, 0x63, 0x1f, 0xea, 0x45, 0x93, 0x41, 0x28, 0x2f, 0x3d, 0x5f, 0xe8,
	0x8d, 0xb8, 0x0f, 0xcd, 0x39, 0x78, 0xba, 0xbd, 0x68, 0x72, 0x26, 0x67, 0x81, 0x42, 0x8c, 0x89,
	0x2f, 0x4a, 0x7f, 0x1c, 0x9f, 0xee, 0x12, 0xdb, 0xf8, 0xbd, 0x06, 0x7b, 0x88, 0x9d, 0xfc, 0x1d,
	0xbb, 0xbf, 0x05, 0xe0, 0xfb, 0x01, 0x0f, 0x35, 0x87, 0xf8, 0x39, 0x03, 0x5f, 0xad, 0xf7, 0xc3,
	0x18, 0x9d, 0x12, 0x8c, 0x49, 0xd6, 0xf8, 0x7b, 0x19, 0xaa, 0x29, 0xab, 0xf0, 0xa6, 0xdd, 0x7b,
	0xbd, 0xb1, 0xcd, 0xbd, 0x9b, 0x05, 0xae, 0x9f, 0xa2, 0x2f, 0xa1, 0x10, 0xc0, 0xc3, 0xdb, 0x48,
	0x89, 0x89, 0xdb, 0x1a, 0x87, 0x72, 0x36, 0x4d, 0x90, 0xb7, 0xc8, 0xc4, 0x43, 0xb4, 0xe4, 0xc0,
	0xbb, 0x91, 0x2a, 0xc1, 0x5c, 0x4a, 0x62, 0x31, 0x2d, 0x49, 0x45, 0xeb, 0xd8, 0xbe, 0x7f, 0x61,
	0x3b, 0xd7, 0x09, 0xc8, 0x96, 0xd9, 0x08, 0x71, 0x4b, 0x5a, 0xe2, 0xf3, 0x47, 0x71, 0x1b, 0xce,
	0x5f, 0x56, 0x0b, 0x3c, 0x3c, 0x56, 0xcc, 0xc7, 0x17, 0x51, 0xfa, 0xbc, 0xca, 0x68, 0xcc, 0xd1,
	0x92, 0xc3, 0xd9, 0x45, 0x28, 0xec, 0xa9, 0x08, 0x13, 0x98, 0xe5, 0x59, 0x58, 0x99, 0x8f, 0x42,
	0x4c, 0x75, 0xa0, 0x2d, 0x5a, 0x63, 0x7e, 0x2d, 0x19, 0x44, 0xd2, 0x17, 0x43, 0xe9, 0x5c, 0x0b,
	0xa5, 0xd7, 0xe2, 0x0b, 0xba, 0xc0, 0xc4, 0xfc, 0xda, 0x42, 0xd9, 0xca, 0xb9, 0x22, 0x90, 0x56,
	0x79, 0x4a, 0x12, 0xb0, 0x3d, 0x17, 0x81, 0x4e, 0x10, 0xdd, 0xe6, 0x29, 0x49, 0x97, 0x3a, 0x14,
	0x78, 0x6e, 0x02, 0xdf, 0xc5, 0x75, 0x42, 0x61, 0x9e, 0x65, 0xbc, 0x58, 0x40, 0xcf, 0xfa, 0xe6,
	0x73, 0xfc, 0x07, 0x0d, 0xaa, 0xe9, 0x1f, 0x15, 0xf6, 0x04, 0x18, 0x0e, 0xdf, 0xe1, 0xa8, 0xc9,
	0x47, 0xe7, 0x83, 0x4f, 0x9d, 0x66, 0xb7, 0x67, 0xe2, 0x5f, 0x92, 0x3a, 0x00, 0xf2, 0x3f, 0x76,
	0x7b, 0x48, 0x6b, 0x6c, 0x07, 0xaa, 0x48, 0x77, 0xdb, 0x3d, 0xb3, 0x51, 0x62, 0x7b, 0x50, 0x43,
	0x8a, 0x9f, 0x5b, 0x56, 0xd7, 0xfa, 0xae, 0x51, 0x4e, 0x19, 0x03, 0xd3, 0x6a, 0x23, 0xa3, 0xc2,
	0xf6, 0xa1, 0x41, 0x76, 0xcd, 0x9c, 0xd5, 0x8d, 0xd4, 0x4a, 0xbb, 0x6f, 0x99, 0x8d, 0xcd, 0xe3,
	0xdf, 0xc0, 0xde, 0xd2, 0xdf, 0x2e, 0xd6, 0x80, 0x9d, 0xd6, 0x7b, 0xb3, 0xf5, 0x71, 0xd0, 0xef,
	0x5a, 0x23, 0x0a, 0xe4, 0xff, 0xe1, 0xf1, 0x9c, 0x93, 0x5a, 0xa2, 0x78, 0xb8, 0x39, 0x1c, 0xf5,
	0xb9, 0xd9, 0x6e, 0x94, 0x18, 0x83, 0x7a, 0x42, 0xa5, 0x12, 0xe5, 0xd3, 0x7f, 0x6d, 0x41, 0x0d,
	0xff, 0x1c, 0x0f, 0x63, 0xac, 0xb3, 0x0e, 0x54, 0xa8, 0x45, 0x3c, 0xbd, 0xfb, 0xfb, 0xcf, 0xc1,
	0x1d, 0xfb, 0x54, 0xd4, 0x3e, 0x6c, 0x25, 0x35, 0x66, 0x5f, 0xdd, 0xfb, 0x75, 0xe6, 0xe0, 0x6e,
	0x11, 0x32, 0x68, 0x13, 0x68, 0xe6, 0x23, 0x9b, 0xbd, 0x58, 0xfb, 0x7f, 0x63, 0xf1, 0x81, 0x70,
	0xf0, 0x10, 0x41, 0x72, 0xf1, 0xdb, 0xfc, 0xf7, 0x81, 0x24, 0xf8, 0xe3, 0x7b, 0x94, 0xf3, 0x59,
	0x3c, 0x50, 0x96, 0x7c, 0xf1, 0xb8, 0x7b, 0x50, 0x26, 0xc6, 0xfa, 0x86, 0x93, 0x25, 0x71, 0x8f,
	0x0c, 0xd9, 0xfc, 0x35, 0xd4, 0x72, 0xd8, 0x66, 0xdf, 0xac, 0x57, 0xc9, 0x47, 0x7d, 0xbf, 0x18,
	0x19, 0x3f, 0x4f, 0xbe, 0x5a, 0xd0, 0x97, 0x94, 0x35, 0x0f, 0xf5, 0x85, 0x0f, 0x54, 0x07, 0xf7,
	0x09, 0x91, 0xd9, 0x0b, 0xd8, 0xc9, 0x7f, 0xf6, 0x61, 0x6b, 0x1e, 0xef, 0xcb, 0x9f, 0x86, 0x0e,
	0x1e, 0x20, 0x87, 0x41, 0x1c, 0x69, 0xaf, 0x35, 0x16, 0xc0, 0x7e, 0xd1, 0x9f, 0x16, 0x76, 0xb2,
	0xe6, 0xbc, 0xd6, 0xfc, 0xc1, 0x59, 0x77, 0x06, 0xf9, 0xaf, 0x44, 0xe4, 0x4f, 0x01, 0x5b, 0x7d,
	0xd8, 0xb2, 0x97, 0xc5, 0xda, 0xc5, 0xff, 0x8c, 0x0e, 0x1e, 0x2c, 0x8d, 0x91, 0xa1, 0xd7, 0x77,
	0x2f, 0x7f, 0x75, 0x3c, 0xf6, 0xd4, 0xd5, 0xec, 0xe2, 0xc4, 0x91, 0x93, 0x57, 0xb1, 0x76, 0xfa,
	0x63, 0x4f, 0xbd, 0x57, 0xa9, 0xa1, 0x57, 0x68, 0xe8, 0x62, 0x93, 0xbe, 0x1d, 0xbf, 0xf9, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x52, 0xa9, 0xef, 0x49, 0x16, 0x00, 0x00,
}
