/*
Cloud Hypervisor API

Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RateLimitGroupConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RateLimitGroupConfig{}

// RateLimitGroupConfig struct for RateLimitGroupConfig
type RateLimitGroupConfig struct {
	Id string `json:"id"`
	RateLimiterConfig RateLimiterConfig `json:"rate_limiter_config"`
}

type _RateLimitGroupConfig RateLimitGroupConfig

// NewRateLimitGroupConfig instantiates a new RateLimitGroupConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRateLimitGroupConfig(id string, rateLimiterConfig RateLimiterConfig) *RateLimitGroupConfig {
	this := RateLimitGroupConfig{}
	this.Id = id
	this.RateLimiterConfig = rateLimiterConfig
	return &this
}

// NewRateLimitGroupConfigWithDefaults instantiates a new RateLimitGroupConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRateLimitGroupConfigWithDefaults() *RateLimitGroupConfig {
	this := RateLimitGroupConfig{}
	return &this
}

// GetId returns the Id field value
func (o *RateLimitGroupConfig) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RateLimitGroupConfig) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RateLimitGroupConfig) SetId(v string) {
	o.Id = v
}

// GetRateLimiterConfig returns the RateLimiterConfig field value
func (o *RateLimitGroupConfig) GetRateLimiterConfig() RateLimiterConfig {
	if o == nil {
		var ret RateLimiterConfig
		return ret
	}

	return o.RateLimiterConfig
}

// GetRateLimiterConfigOk returns a tuple with the RateLimiterConfig field value
// and a boolean to check if the value has been set.
func (o *RateLimitGroupConfig) GetRateLimiterConfigOk() (*RateLimiterConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RateLimiterConfig, true
}

// SetRateLimiterConfig sets field value
func (o *RateLimitGroupConfig) SetRateLimiterConfig(v RateLimiterConfig) {
	o.RateLimiterConfig = v
}

func (o RateLimitGroupConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RateLimitGroupConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["rate_limiter_config"] = o.RateLimiterConfig
	return toSerialize, nil
}

func (o *RateLimitGroupConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"rate_limiter_config",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRateLimitGroupConfig := _RateLimitGroupConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRateLimitGroupConfig)

	if err != nil {
		return err
	}

	*o = RateLimitGroupConfig(varRateLimitGroupConfig)

	return err
}

type NullableRateLimitGroupConfig struct {
	value *RateLimitGroupConfig
	isSet bool
}

func (v NullableRateLimitGroupConfig) Get() *RateLimitGroupConfig {
	return v.value
}

func (v *NullableRateLimitGroupConfig) Set(val *RateLimitGroupConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableRateLimitGroupConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableRateLimitGroupConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRateLimitGroupConfig(val *RateLimitGroupConfig) *NullableRateLimitGroupConfig {
	return &NullableRateLimitGroupConfig{value: val, isSet: true}
}

func (v NullableRateLimitGroupConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRateLimitGroupConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


