version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: cedana
    builder: prebuilt
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v1
    binary: cedana
    ldflags:
      - -X main.Version={{ .Summary }}
    prebuilt:
      path: ./cedana
  - id: libcedana-runc
    builder: prebuilt
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v1
    main: ./plugins/runc
    binary: libcedana-runc.so
    buildmode: plugin
    no_main_check: true
    ldflags:
      - -X main.Version={{ .Summary }}
    prebuilt:
      path: ./libcedana-runc.so
  - id: libcedana-containerd
    builder: prebuilt
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v1
    main: ./plugins/containerd
    binary: libcedana-containerd.so
    buildmode: plugin
    no_main_check: true
    ldflags:
      - -X main.Version={{ .Summary }}
    prebuilt:
      path: ./libcedana-containerd.so
  - id: libcedana-crio
    builder: prebuilt
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v1
    main: ./plugins/crio
    binary: libcedana-crio.so
    buildmode: plugin
    no_main_check: true
    ldflags:
      - -X main.Version={{ .Summary }}
    prebuilt:
      path: ./libcedana-crio.so
  - id: libcedana-k8s
    builder: prebuilt
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v1
    main: ./plugins/k8s
    binary: libcedana-k8s.so
    buildmode: plugin
    no_main_check: true
    ldflags:
      - -X main.Version={{ .Summary }}
    prebuilt:
      path: ./libcedana-k8s.so
  - id: libcedana-cloud-hypervisor
    builder: prebuilt
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v1
    main: ./plugins/cloud-hypervisor
    binary: libcedana-cloud-hypervisor.so
    buildmode: plugin
    no_main_check: true
    ldflags:
      - -X main.Version={{ .Summary }}
    prebuilt:
      path: ./libcedana-cloud-hypervisor.so
  - id: libcedana-kata
    builder: prebuilt
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v1
    main: ./plugins/kata
    binary: libcedana-kata.so
    buildmode: plugin
    no_main_check: true
    ldflags:
      - -X main.Version={{ .Summary }}
    prebuilt:
      path: ./libcedana-kata.so

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Summary }}"

changelog:
  sort: desc
  use: github
  filters:
    exclude:
      - "^GITBOOK-"


archives:
  - id: cedana
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds: [cedana]
    files: [./scripts/*]
  - id: libcedana-runc
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds: [libcedana-runc]
  - id: libcedana-containerd
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds: [libcedana-containerd]
  - id: libcedana-crio
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds: [libcedana-crio]
  - id: libcedana-k8s
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds: [libcedana-k8s]
