before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - 
    id: default
    package_name: cedana
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Cedana Corp

    homepage: cedana.ai
    maintainer: Niranjan Ravichandra <nravic@cedana.ai>

    description: |-
      Fast, adaptive checkpointing for orchestrated cloud brokerage.

    license: GNU APLv3

    formats:
      - deb
      - rpm
      - archlinux  # Since GoReleaser v1.13.
    
    suggests:
      - criu 

archives:
  - id: cedana
