// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: runc.proto

package runc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Details struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Bundle string `protobuf:"bytes,2,opt,name=Bundle,proto3" json:"Bundle,omitempty"`
	Root   string `protobuf:"bytes,3,opt,name=Root,proto3" json:"Root,omitempty"`
}

func (x *Details) Reset() {
	*x = Details{}
	mi := &file_runc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Details) ProtoMessage() {}

func (x *Details) ProtoReflect() protoreflect.Message {
	mi := &file_runc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Details.ProtoReflect.Descriptor instead.
func (*Details) Descriptor() ([]byte, []int) {
	return file_runc_proto_rawDescGZIP(), []int{0}
}

func (x *Details) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Details) GetBundle() string {
	if x != nil {
		return x.Bundle
	}
	return ""
}

func (x *Details) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type StartDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Bundle string `protobuf:"bytes,2,opt,name=Bundle,proto3" json:"Bundle,omitempty"`
	Root   string `protobuf:"bytes,3,opt,name=Root,proto3" json:"Root,omitempty"`
}

func (x *StartDetails) Reset() {
	*x = StartDetails{}
	mi := &file_runc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDetails) ProtoMessage() {}

func (x *StartDetails) ProtoReflect() protoreflect.Message {
	mi := &file_runc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDetails.ProtoReflect.Descriptor instead.
func (*StartDetails) Descriptor() ([]byte, []int) {
	return file_runc_proto_rawDescGZIP(), []int{1}
}

func (x *StartDetails) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *StartDetails) GetBundle() string {
	if x != nil {
		return x.Bundle
	}
	return ""
}

func (x *StartDetails) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

var File_runc_proto protoreflect.FileDescriptor

var file_runc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x65,
	0x64, 0x61, 0x6e, 0x61, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x72, 0x75, 0x6e,
	0x63, 0x22, 0x45, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x75,
	0x6e, 0x64, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x52, 0x6f, 0x6f, 0x74, 0x22, 0x4a, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x75, 0x6e, 0x64,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x52, 0x6f, 0x6f, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_runc_proto_rawDescOnce sync.Once
	file_runc_proto_rawDescData = file_runc_proto_rawDesc
)

func file_runc_proto_rawDescGZIP() []byte {
	file_runc_proto_rawDescOnce.Do(func() {
		file_runc_proto_rawDescData = protoimpl.X.CompressGZIP(file_runc_proto_rawDescData)
	})
	return file_runc_proto_rawDescData
}

var file_runc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_runc_proto_goTypes = []any{
	(*Details)(nil),      // 0: cedana.plugins.runc.Details
	(*StartDetails)(nil), // 1: cedana.plugins.runc.StartDetails
}
var file_runc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runc_proto_init() }
func file_runc_proto_init() {
	if File_runc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runc_proto_goTypes,
		DependencyIndexes: file_runc_proto_depIdxs,
		MessageInfos:      file_runc_proto_msgTypes,
	}.Build()
	File_runc_proto = out.File
	file_runc_proto_rawDesc = nil
	file_runc_proto_goTypes = nil
	file_runc_proto_depIdxs = nil
}
