// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/cedana.proto

package cedana_orch

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Encapsulates data required for the server to make checkpointing decisions
type ClientData struct {
	ClientInfo           *ClientInfo  `protobuf:"bytes,1,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	ProcessInfo          *ProcessInfo `protobuf:"bytes,2,opt,name=process_info,json=processInfo,proto3" json:"process_info,omitempty"`
	State                *ClientState `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ClientData) Reset()         { *m = ClientData{} }
func (m *ClientData) String() string { return proto.CompactTextString(m) }
func (*ClientData) ProtoMessage()    {}
func (*ClientData) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{0}
}

func (m *ClientData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientData.Unmarshal(m, b)
}
func (m *ClientData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientData.Marshal(b, m, deterministic)
}
func (m *ClientData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientData.Merge(m, src)
}
func (m *ClientData) XXX_Size() int {
	return xxx_messageInfo_ClientData.Size(m)
}
func (m *ClientData) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientData.DiscardUnknown(m)
}

var xxx_messageInfo_ClientData proto.InternalMessageInfo

func (m *ClientData) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

func (m *ClientData) GetProcessInfo() *ProcessInfo {
	if m != nil {
		return m.ProcessInfo
	}
	return nil
}

func (m *ClientData) GetState() *ClientState {
	if m != nil {
		return m.State
	}
	return nil
}

type ClientInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Os                   string   `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Platform             string   `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{1}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClientInfo) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *ClientInfo) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

type ClientState struct {
	RemainingMemory      int32           `protobuf:"varint,1,opt,name=remaining_memory,json=remainingMemory,proto3" json:"remaining_memory,omitempty"`
	Uptime               int32           `protobuf:"varint,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Network              *ConnectionStat `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ClientState) Reset()         { *m = ClientState{} }
func (m *ClientState) String() string { return proto.CompactTextString(m) }
func (*ClientState) ProtoMessage()    {}
func (*ClientState) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{2}
}

func (m *ClientState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientState.Unmarshal(m, b)
}
func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientState.Marshal(b, m, deterministic)
}
func (m *ClientState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientState.Merge(m, src)
}
func (m *ClientState) XXX_Size() int {
	return xxx_messageInfo_ClientState.Size(m)
}
func (m *ClientState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientState.DiscardUnknown(m)
}

var xxx_messageInfo_ClientState proto.InternalMessageInfo

func (m *ClientState) GetRemainingMemory() int32 {
	if m != nil {
		return m.RemainingMemory
	}
	return 0
}

func (m *ClientState) GetUptime() int32 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *ClientState) GetNetwork() *ConnectionStat {
	if m != nil {
		return m.Network
	}
	return nil
}

type DockerInfo struct {
	CgroupMem            uint32   `protobuf:"varint,1,opt,name=cgroup_mem,json=cgroupMem,proto3" json:"cgroup_mem,omitempty"`
	CgroupCpu            uint32   `protobuf:"varint,2,opt,name=cgroup_cpu,json=cgroupCpu,proto3" json:"cgroup_cpu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DockerInfo) Reset()         { *m = DockerInfo{} }
func (m *DockerInfo) String() string { return proto.CompactTextString(m) }
func (*DockerInfo) ProtoMessage()    {}
func (*DockerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{3}
}

func (m *DockerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockerInfo.Unmarshal(m, b)
}
func (m *DockerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockerInfo.Marshal(b, m, deterministic)
}
func (m *DockerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockerInfo.Merge(m, src)
}
func (m *DockerInfo) XXX_Size() int {
	return xxx_messageInfo_DockerInfo.Size(m)
}
func (m *DockerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DockerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DockerInfo proto.InternalMessageInfo

func (m *DockerInfo) GetCgroupMem() uint32 {
	if m != nil {
		return m.CgroupMem
	}
	return 0
}

func (m *DockerInfo) GetCgroupCpu() uint32 {
	if m != nil {
		return m.CgroupCpu
	}
	return 0
}

type NetworkAddr struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkAddr) Reset()         { *m = NetworkAddr{} }
func (m *NetworkAddr) String() string { return proto.CompactTextString(m) }
func (*NetworkAddr) ProtoMessage()    {}
func (*NetworkAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{4}
}

func (m *NetworkAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkAddr.Unmarshal(m, b)
}
func (m *NetworkAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkAddr.Marshal(b, m, deterministic)
}
func (m *NetworkAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkAddr.Merge(m, src)
}
func (m *NetworkAddr) XXX_Size() int {
	return xxx_messageInfo_NetworkAddr.Size(m)
}
func (m *NetworkAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkAddr.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkAddr proto.InternalMessageInfo

func (m *NetworkAddr) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NetworkAddr) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// lifted from gopsutil
type ConnectionStat struct {
	Fd                   uint32       `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	Family               uint32       `protobuf:"varint,2,opt,name=family,proto3" json:"family,omitempty"`
	Type                 uint32       `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Laddr                *NetworkAddr `protobuf:"bytes,4,opt,name=laddr,proto3" json:"laddr,omitempty"`
	Raddr                *NetworkAddr `protobuf:"bytes,5,opt,name=raddr,proto3" json:"raddr,omitempty"`
	Status               string       `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Uids                 []int32      `protobuf:"varint,7,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConnectionStat) Reset()         { *m = ConnectionStat{} }
func (m *ConnectionStat) String() string { return proto.CompactTextString(m) }
func (*ConnectionStat) ProtoMessage()    {}
func (*ConnectionStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{5}
}

func (m *ConnectionStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionStat.Unmarshal(m, b)
}
func (m *ConnectionStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionStat.Marshal(b, m, deterministic)
}
func (m *ConnectionStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionStat.Merge(m, src)
}
func (m *ConnectionStat) XXX_Size() int {
	return xxx_messageInfo_ConnectionStat.Size(m)
}
func (m *ConnectionStat) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionStat.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionStat proto.InternalMessageInfo

func (m *ConnectionStat) GetFd() uint32 {
	if m != nil {
		return m.Fd
	}
	return 0
}

func (m *ConnectionStat) GetFamily() uint32 {
	if m != nil {
		return m.Family
	}
	return 0
}

func (m *ConnectionStat) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ConnectionStat) GetLaddr() *NetworkAddr {
	if m != nil {
		return m.Laddr
	}
	return nil
}

func (m *ConnectionStat) GetRaddr() *NetworkAddr {
	if m != nil {
		return m.Raddr
	}
	return nil
}

func (m *ConnectionStat) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ConnectionStat) GetUids() []int32 {
	if m != nil {
		return m.Uids
	}
	return nil
}

type ProcessInfo struct {
	ProcessPid           uint32   `protobuf:"varint,1,opt,name=process_pid,json=processPid,proto3" json:"process_pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessInfo) Reset()         { *m = ProcessInfo{} }
func (m *ProcessInfo) String() string { return proto.CompactTextString(m) }
func (*ProcessInfo) ProtoMessage()    {}
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{6}
}

func (m *ProcessInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessInfo.Unmarshal(m, b)
}
func (m *ProcessInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessInfo.Marshal(b, m, deterministic)
}
func (m *ProcessInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessInfo.Merge(m, src)
}
func (m *ProcessInfo) XXX_Size() int {
	return xxx_messageInfo_ProcessInfo.Size(m)
}
func (m *ProcessInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessInfo proto.InternalMessageInfo

func (m *ProcessInfo) GetProcessPid() uint32 {
	if m != nil {
		return m.ProcessPid
	}
	return 0
}

type ClientStateAck struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Acked                bool     `protobuf:"varint,2,opt,name=acked,proto3" json:"acked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientStateAck) Reset()         { *m = ClientStateAck{} }
func (m *ClientStateAck) String() string { return proto.CompactTextString(m) }
func (*ClientStateAck) ProtoMessage()    {}
func (*ClientStateAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{7}
}

func (m *ClientStateAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientStateAck.Unmarshal(m, b)
}
func (m *ClientStateAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientStateAck.Marshal(b, m, deterministic)
}
func (m *ClientStateAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientStateAck.Merge(m, src)
}
func (m *ClientStateAck) XXX_Size() int {
	return xxx_messageInfo_ClientStateAck.Size(m)
}
func (m *ClientStateAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientStateAck.DiscardUnknown(m)
}

var xxx_messageInfo_ClientStateAck proto.InternalMessageInfo

func (m *ClientStateAck) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ClientStateAck) GetAcked() bool {
	if m != nil {
		return m.Acked
	}
	return false
}

type ClientCommand struct {
	Checkpoint           bool                `protobuf:"varint,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	Restore              bool                `protobuf:"varint,2,opt,name=restore,proto3" json:"restore,omitempty"`
	Transfer             *TransferCheckpoint `protobuf:"bytes,3,opt,name=transfer,proto3" json:"transfer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ClientCommand) Reset()         { *m = ClientCommand{} }
func (m *ClientCommand) String() string { return proto.CompactTextString(m) }
func (*ClientCommand) ProtoMessage()    {}
func (*ClientCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{8}
}

func (m *ClientCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientCommand.Unmarshal(m, b)
}
func (m *ClientCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientCommand.Marshal(b, m, deterministic)
}
func (m *ClientCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientCommand.Merge(m, src)
}
func (m *ClientCommand) XXX_Size() int {
	return xxx_messageInfo_ClientCommand.Size(m)
}
func (m *ClientCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ClientCommand proto.InternalMessageInfo

func (m *ClientCommand) GetCheckpoint() bool {
	if m != nil {
		return m.Checkpoint
	}
	return false
}

func (m *ClientCommand) GetRestore() bool {
	if m != nil {
		return m.Restore
	}
	return false
}

func (m *ClientCommand) GetTransfer() *TransferCheckpoint {
	if m != nil {
		return m.Transfer
	}
	return nil
}

type TransferCheckpoint struct {
	Transfer             bool     `protobuf:"varint,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferCheckpoint) Reset()         { *m = TransferCheckpoint{} }
func (m *TransferCheckpoint) String() string { return proto.CompactTextString(m) }
func (*TransferCheckpoint) ProtoMessage()    {}
func (*TransferCheckpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{9}
}

func (m *TransferCheckpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferCheckpoint.Unmarshal(m, b)
}
func (m *TransferCheckpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferCheckpoint.Marshal(b, m, deterministic)
}
func (m *TransferCheckpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferCheckpoint.Merge(m, src)
}
func (m *TransferCheckpoint) XXX_Size() int {
	return xxx_messageInfo_TransferCheckpoint.Size(m)
}
func (m *TransferCheckpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferCheckpoint.DiscardUnknown(m)
}

var xxx_messageInfo_TransferCheckpoint proto.InternalMessageInfo

func (m *TransferCheckpoint) GetTransfer() bool {
	if m != nil {
		return m.Transfer
	}
	return false
}

func (m *TransferCheckpoint) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

// Client config is added to the protobuf defs so it's shared across
// the client and orchestrator (without needing the orchestrator to depend on it)/
// We might also eventually want to be sending updates to the config over the wire.
type ConfigClient struct {
	Client               *Client        `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	ActionScripts        *ActionScripts `protobuf:"bytes,2,opt,name=action_scripts,json=actionScripts,proto3" json:"action_scripts,omitempty"`
	Connection           *Connection    `protobuf:"bytes,3,opt,name=connection,proto3" json:"connection,omitempty"`
	Aws                  *AWS           `protobuf:"bytes,4,opt,name=aws,proto3" json:"aws,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ConfigClient) Reset()         { *m = ConfigClient{} }
func (m *ConfigClient) String() string { return proto.CompactTextString(m) }
func (*ConfigClient) ProtoMessage()    {}
func (*ConfigClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{10}
}

func (m *ConfigClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigClient.Unmarshal(m, b)
}
func (m *ConfigClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigClient.Marshal(b, m, deterministic)
}
func (m *ConfigClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigClient.Merge(m, src)
}
func (m *ConfigClient) XXX_Size() int {
	return xxx_messageInfo_ConfigClient.Size(m)
}
func (m *ConfigClient) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigClient.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigClient proto.InternalMessageInfo

func (m *ConfigClient) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *ConfigClient) GetActionScripts() *ActionScripts {
	if m != nil {
		return m.ActionScripts
	}
	return nil
}

func (m *ConfigClient) GetConnection() *Connection {
	if m != nil {
		return m.Connection
	}
	return nil
}

func (m *ConfigClient) GetAws() *AWS {
	if m != nil {
		return m.Aws
	}
	return nil
}

type Client struct {
	ProcessName          string   `protobuf:"bytes,1,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	DumpFrequencyMin     int32    `protobuf:"varint,2,opt,name=dump_frequency_min,json=dumpFrequencyMin,proto3" json:"dump_frequency_min,omitempty"`
	DumpStorageDir       string   `protobuf:"bytes,3,opt,name=dump_storage_dir,json=dumpStorageDir,proto3" json:"dump_storage_dir,omitempty"`
	LeaveRunning         bool     `protobuf:"varint,4,opt,name=leave_running,json=leaveRunning,proto3" json:"leave_running,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{11}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *Client) GetDumpFrequencyMin() int32 {
	if m != nil {
		return m.DumpFrequencyMin
	}
	return 0
}

func (m *Client) GetDumpStorageDir() string {
	if m != nil {
		return m.DumpStorageDir
	}
	return ""
}

func (m *Client) GetLeaveRunning() bool {
	if m != nil {
		return m.LeaveRunning
	}
	return false
}

type ActionScripts struct {
	PreDump              string   `protobuf:"bytes,1,opt,name=pre_dump,json=preDump,proto3" json:"pre_dump,omitempty"`
	PostDump             string   `protobuf:"bytes,2,opt,name=post_dump,json=postDump,proto3" json:"post_dump,omitempty"`
	PreRestore           string   `protobuf:"bytes,3,opt,name=pre_restore,json=preRestore,proto3" json:"pre_restore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionScripts) Reset()         { *m = ActionScripts{} }
func (m *ActionScripts) String() string { return proto.CompactTextString(m) }
func (*ActionScripts) ProtoMessage()    {}
func (*ActionScripts) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{12}
}

func (m *ActionScripts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionScripts.Unmarshal(m, b)
}
func (m *ActionScripts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionScripts.Marshal(b, m, deterministic)
}
func (m *ActionScripts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionScripts.Merge(m, src)
}
func (m *ActionScripts) XXX_Size() int {
	return xxx_messageInfo_ActionScripts.Size(m)
}
func (m *ActionScripts) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionScripts.DiscardUnknown(m)
}

var xxx_messageInfo_ActionScripts proto.InternalMessageInfo

func (m *ActionScripts) GetPreDump() string {
	if m != nil {
		return m.PreDump
	}
	return ""
}

func (m *ActionScripts) GetPostDump() string {
	if m != nil {
		return m.PostDump
	}
	return ""
}

func (m *ActionScripts) GetPreRestore() string {
	if m != nil {
		return m.PreRestore
	}
	return ""
}

type Connection struct {
	ServerAddr           string   `protobuf:"bytes,1,opt,name=server_addr,json=serverAddr,proto3" json:"server_addr,omitempty"`
	ServerPort           uint32   `protobuf:"varint,2,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{13}
}

func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (m *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(m, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetServerAddr() string {
	if m != nil {
		return m.ServerAddr
	}
	return ""
}

func (m *Connection) GetServerPort() uint32 {
	if m != nil {
		return m.ServerPort
	}
	return 0
}

type AWS struct {
	EfsId                string   `protobuf:"bytes,1,opt,name=efs_id,json=efsId,proto3" json:"efs_id,omitempty"`
	EfsMountPoint        string   `protobuf:"bytes,2,opt,name=efs_mount_point,json=efsMountPoint,proto3" json:"efs_mount_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AWS) Reset()         { *m = AWS{} }
func (m *AWS) String() string { return proto.CompactTextString(m) }
func (*AWS) ProtoMessage()    {}
func (*AWS) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f75f48e5338b9f, []int{14}
}

func (m *AWS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AWS.Unmarshal(m, b)
}
func (m *AWS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AWS.Marshal(b, m, deterministic)
}
func (m *AWS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AWS.Merge(m, src)
}
func (m *AWS) XXX_Size() int {
	return xxx_messageInfo_AWS.Size(m)
}
func (m *AWS) XXX_DiscardUnknown() {
	xxx_messageInfo_AWS.DiscardUnknown(m)
}

var xxx_messageInfo_AWS proto.InternalMessageInfo

func (m *AWS) GetEfsId() string {
	if m != nil {
		return m.EfsId
	}
	return ""
}

func (m *AWS) GetEfsMountPoint() string {
	if m != nil {
		return m.EfsMountPoint
	}
	return ""
}

func init() {
	proto.RegisterType((*ClientData)(nil), "cedana.ClientData")
	proto.RegisterType((*ClientInfo)(nil), "cedana.ClientInfo")
	proto.RegisterType((*ClientState)(nil), "cedana.ClientState")
	proto.RegisterType((*DockerInfo)(nil), "cedana.DockerInfo")
	proto.RegisterType((*NetworkAddr)(nil), "cedana.NetworkAddr")
	proto.RegisterType((*ConnectionStat)(nil), "cedana.ConnectionStat")
	proto.RegisterType((*ProcessInfo)(nil), "cedana.ProcessInfo")
	proto.RegisterType((*ClientStateAck)(nil), "cedana.ClientStateAck")
	proto.RegisterType((*ClientCommand)(nil), "cedana.ClientCommand")
	proto.RegisterType((*TransferCheckpoint)(nil), "cedana.TransferCheckpoint")
	proto.RegisterType((*ConfigClient)(nil), "cedana.ConfigClient")
	proto.RegisterType((*Client)(nil), "cedana.Client")
	proto.RegisterType((*ActionScripts)(nil), "cedana.ActionScripts")
	proto.RegisterType((*Connection)(nil), "cedana.Connection")
	proto.RegisterType((*AWS)(nil), "cedana.AWS")
}

func init() { proto.RegisterFile("rpc/cedana.proto", fileDescriptor_05f75f48e5338b9f) }

var fileDescriptor_05f75f48e5338b9f = []byte{
	// 915 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xee, 0xda, 0xb5, 0x63, 0xbf, 0x8e, 0x9d, 0x68, 0x68, 0x22, 0x13, 0x28, 0x94, 0x45, 0xaa,
	0x52, 0x09, 0x42, 0x49, 0xa5, 0x9e, 0xe0, 0x60, 0x6c, 0x55, 0x14, 0x91, 0xc8, 0x9a, 0x20, 0x55,
	0xe2, 0xb2, 0x1a, 0x66, 0x67, 0x9d, 0x91, 0x77, 0x67, 0x86, 0x99, 0xd9, 0x56, 0x39, 0xc2, 0x6f,
	0xe1, 0xc0, 0x3f, 0x81, 0x13, 0xbf, 0x09, 0xcd, 0xc7, 0xae, 0xd7, 0x34, 0xe2, 0x36, 0xef, 0xf3,
	0x7e, 0x7f, 0x0e, 0x1c, 0x6b, 0x45, 0xbf, 0xa2, 0x2c, 0x27, 0x82, 0x5c, 0x28, 0x2d, 0xad, 0x44,
	0xc3, 0x40, 0xa5, 0x7f, 0x24, 0x00, 0xcb, 0x92, 0x33, 0x61, 0x57, 0xc4, 0x12, 0xf4, 0x02, 0x26,
	0xd4, 0x53, 0x19, 0x17, 0x85, 0x9c, 0x27, 0x4f, 0x92, 0xf3, 0xc9, 0x25, 0xba, 0x88, 0xaa, 0x41,
	0xf0, 0xb5, 0x28, 0x24, 0x06, 0xda, 0xbe, 0xd1, 0x4b, 0x38, 0x54, 0x5a, 0x52, 0x66, 0x4c, 0xd0,
	0xea, 0x79, 0xad, 0x0f, 0x1a, 0xad, 0x75, 0xe0, 0x79, 0xb5, 0x89, 0xda, 0x11, 0xe8, 0x19, 0x0c,
	0x8c, 0x25, 0x96, 0xcd, 0xfb, 0xfb, 0x0a, 0xc1, 0xcd, 0x8d, 0x63, 0xe1, 0x20, 0x91, 0x7e, 0xdf,
	0x44, 0xe9, 0x15, 0x67, 0xd0, 0xe3, 0xb9, 0x0f, 0x6e, 0x8c, 0x7b, 0x3c, 0x77, 0xb4, 0x34, 0xde,
	0xed, 0x18, 0xf7, 0xa4, 0x41, 0x67, 0x30, 0x52, 0x25, 0xb1, 0x85, 0xd4, 0x95, 0xb7, 0x3d, 0xc6,
	0x2d, 0x9d, 0xfe, 0x9e, 0xc0, 0xa4, 0xe3, 0x00, 0x3d, 0x83, 0x63, 0xcd, 0x2a, 0xc2, 0x05, 0x17,
	0x9b, 0xac, 0x62, 0x95, 0xd4, 0x77, 0xde, 0xf2, 0x00, 0x1f, 0xb5, 0xf8, 0x95, 0x87, 0xd1, 0x29,
	0x0c, 0x6b, 0x65, 0x79, 0xc5, 0xbc, 0xab, 0x01, 0x8e, 0x14, 0x7a, 0x0e, 0x07, 0x82, 0xd9, 0x77,
	0x52, 0x6f, 0x63, 0x26, 0xa7, 0x6d, 0x26, 0x52, 0x08, 0x46, 0x2d, 0x97, 0xc2, 0x39, 0xc3, 0x8d,
	0x58, 0xfa, 0x03, 0xc0, 0x4a, 0xd2, 0x2d, 0xd3, 0x3e, 0x9d, 0xc7, 0x00, 0x74, 0xa3, 0x65, 0xad,
	0x9c, 0x7f, 0xef, 0x7c, 0x8a, 0xc7, 0x01, 0xb9, 0x62, 0x55, 0x87, 0x4d, 0x55, 0xed, 0x5d, 0xb7,
	0xec, 0xa5, 0xaa, 0xd3, 0xaf, 0x61, 0x72, 0x1d, 0xcc, 0x2e, 0xf2, 0x5c, 0xfb, 0xda, 0xa8, 0xb6,
	0x36, 0x0a, 0x21, 0x78, 0xa8, 0xa4, 0xb6, 0x51, 0xcf, 0xbf, 0xd3, 0x7f, 0x12, 0x98, 0xed, 0x87,
	0xe6, 0xd4, 0x8a, 0x3c, 0xfa, 0xee, 0x15, 0xb9, 0xcb, 0xb5, 0x20, 0x15, 0x2f, 0xef, 0xa2, 0x62,
	0xa4, 0x9c, 0x39, 0x7b, 0xa7, 0x42, 0xcb, 0xa6, 0xd8, 0xbf, 0x5d, 0x1f, 0x4b, 0x92, 0xe7, 0x7a,
	0xfe, 0x70, 0xbf, 0x8f, 0x9d, 0xb0, 0x70, 0x90, 0x70, 0xa2, 0xda, 0x8b, 0x0e, 0xfe, 0x47, 0xd4,
	0x4b, 0xb8, 0x08, 0x5c, 0xef, 0x6b, 0x33, 0x1f, 0xfa, 0x64, 0x22, 0xe5, 0x22, 0xa8, 0x79, 0x6e,
	0xe6, 0x07, 0x4f, 0xfa, 0xe7, 0x03, 0xec, 0xdf, 0xe9, 0x05, 0x4c, 0x3a, 0x53, 0x86, 0x3e, 0x85,
	0x66, 0xce, 0x32, 0xc5, 0x9b, 0xac, 0x20, 0x42, 0x6b, 0x9e, 0xa7, 0x2b, 0x98, 0x75, 0x66, 0x60,
	0x41, 0xb7, 0xe8, 0x63, 0x18, 0xbb, 0x5e, 0x1a, 0x4b, 0xaa, 0x50, 0xbd, 0x3e, 0xde, 0x01, 0xe8,
	0x11, 0x0c, 0x08, 0xdd, 0xb2, 0xdc, 0x17, 0x63, 0x84, 0x03, 0x91, 0xfe, 0x96, 0xc0, 0x34, 0x98,
	0x59, 0xca, 0xaa, 0x22, 0x22, 0x47, 0x9f, 0x00, 0xd0, 0x5b, 0x46, 0xb7, 0x4a, 0x72, 0x61, 0xbd,
	0x99, 0x11, 0xee, 0x20, 0x68, 0x0e, 0x07, 0x9a, 0x19, 0x2b, 0x35, 0x8b, 0x96, 0x1a, 0x12, 0xbd,
	0x84, 0x91, 0xd5, 0x44, 0x98, 0x82, 0xe9, 0x38, 0x44, 0x67, 0x4d, 0x6d, 0x7e, 0x8a, 0xf8, 0xb2,
	0xb5, 0x83, 0x5b, 0xd9, 0xf4, 0x47, 0x40, 0xef, 0xf3, 0xdd, 0x02, 0xb4, 0xd6, 0x42, 0x14, 0x2d,
	0xed, 0x78, 0xa5, 0xa4, 0xc4, 0x75, 0x3e, 0xae, 0x4c, 0x4b, 0xa7, 0x7f, 0x25, 0x70, 0xb8, 0x94,
	0xa2, 0xe0, 0x9b, 0x90, 0x17, 0x7a, 0x0a, 0xc3, 0xb0, 0xe8, 0xf1, 0x14, 0xcc, 0xf6, 0x77, 0x14,
	0x47, 0x2e, 0xfa, 0x06, 0x66, 0xc4, 0x0f, 0x53, 0x66, 0xa8, 0xe6, 0xca, 0x9a, 0x78, 0x04, 0x4e,
	0x1a, 0xf9, 0x45, 0x18, 0xb5, 0xc0, 0xc4, 0x53, 0xd2, 0x25, 0xd1, 0x25, 0x00, 0x6d, 0xc7, 0x31,
	0xa6, 0x8f, 0xde, 0xdf, 0x21, 0xdc, 0x91, 0x42, 0x8f, 0xa1, 0x4f, 0xde, 0x99, 0x38, 0x72, 0x93,
	0xd6, 0xcd, 0x9b, 0x1b, 0xec, 0xf0, 0xf4, 0xcf, 0x04, 0x86, 0x31, 0x87, 0xcf, 0x76, 0xe7, 0x49,
	0x90, 0x8a, 0xc5, 0xdd, 0x68, 0x26, 0xe4, 0x9a, 0x54, 0x0c, 0x7d, 0x01, 0x28, 0xaf, 0x2b, 0x95,
	0x15, 0x9a, 0xfd, 0x5a, 0x33, 0x41, 0xef, 0xb2, 0x8a, 0x8b, 0xb8, 0xe5, 0xc7, 0x8e, 0xf3, 0xaa,
	0x61, 0x5c, 0x71, 0x81, 0xce, 0xc1, 0x63, 0x99, 0xeb, 0x1c, 0xd9, 0xb0, 0x2c, 0xe7, 0x3a, 0x9e,
	0x99, 0x99, 0xc3, 0x6f, 0x02, 0xbc, 0xe2, 0x1a, 0x7d, 0x0e, 0xd3, 0x92, 0x91, 0xb7, 0x2c, 0xd3,
	0xb5, 0x70, 0x87, 0xc4, 0x87, 0x3b, 0xc2, 0x87, 0x1e, 0xc4, 0x01, 0x4b, 0x6f, 0x61, 0xba, 0x57,
	0x1d, 0xf4, 0x21, 0x8c, 0x94, 0x66, 0x99, 0xb3, 0x15, 0x83, 0x3d, 0x50, 0x9a, 0xad, 0xea, 0x4a,
	0xa1, 0x8f, 0x60, 0xac, 0xa4, 0xb1, 0x81, 0x17, 0xbb, 0xe7, 0x00, 0xcf, 0xf4, 0x63, 0xcf, 0xb2,
	0x66, 0xc2, 0x42, 0x48, 0xa0, 0x34, 0xc3, 0x01, 0x49, 0xaf, 0x01, 0x76, 0xd5, 0x74, 0xe2, 0x86,
	0xe9, 0xb7, 0x4c, 0x67, 0x7e, 0x23, 0x83, 0x27, 0x08, 0x90, 0x3f, 0x25, 0x3b, 0x81, 0xce, 0x05,
	0x89, 0x02, 0x6b, 0x77, 0x47, 0x56, 0xd0, 0x5f, 0xbc, 0xb9, 0x41, 0x27, 0x30, 0x64, 0x85, 0xc9,
	0xda, 0x93, 0x3c, 0x60, 0x85, 0x79, 0x9d, 0xa3, 0xa7, 0x70, 0xe4, 0xe0, 0x4a, 0xd6, 0xc2, 0x66,
	0x61, 0x23, 0x42, 0xc4, 0x53, 0x56, 0x98, 0x2b, 0x87, 0xae, 0x1d, 0x78, 0xf9, 0xb7, 0x6b, 0x95,
	0x6f, 0x9f, 0x1b, 0x23, 0xcc, 0x36, 0xdc, 0x58, 0xa6, 0x63, 0xf3, 0xfe, 0xf3, 0xf7, 0xb8, 0x4f,
	0xea, 0xec, 0x51, 0x67, 0x34, 0xda, 0x51, 0x4d, 0x1f, 0xa0, 0x6f, 0x61, 0x82, 0x19, 0x95, 0x3a,
	0x0f, 0x97, 0xfd, 0x3e, 0xd5, 0xd3, 0x7b, 0xfe, 0x98, 0x05, 0xdd, 0xa6, 0x0f, 0xce, 0x13, 0xb4,
	0x80, 0xd9, 0x5a, 0x96, 0xe5, 0x2b, 0xa9, 0x9b, 0x75, 0xbe, 0xcf, 0xc2, 0xc9, 0x3e, 0x16, 0x45,
	0x9d, 0x81, 0xe7, 0xc9, 0x77, 0x47, 0x3f, 0x4f, 0x2f, 0xe2, 0x3f, 0xfb, 0xa5, 0xd4, 0xf4, 0xf6,
	0x97, 0xa1, 0xff, 0x6d, 0x5f, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x19, 0x48, 0xcf, 0x90, 0x81,
	0x07, 0x00, 0x00,
}
