package keys

// Defines common keys used in this plugin

const (
	CONTAINER_CONTEXT_KEY = 999 + iota
	CONTAINER_CGROUP_MANAGER_CONTEXT_KEY
	INIT_PROCESS_CONTEXT_KEY
	SPEC_CONTEXT_KEY
	SIGNAL_HANDLER_CONTEXT_KEY
	TTY_CONTEXT_KEY
)
