package cmd

// This file contains all the flags used in the cmd package

const (
	dirFlag              = "dir"
	imgFlag              = "image"
	idFlag               = "id"
	refFlag              = "ref"
	newRefFlag           = "new-ref"
	rootfsDiffPathFlag   = "rootfs-diff-path"
	addressFlag          = "address"
	namespaceFlag        = "namespace"
	rootFlag             = "root"
	wdFlag               = "working-dir"
	containerNameFlag    = "container-name"
	bundleFlag           = "bundle"
	consoleSocketFlag    = "console-socket"
	detachFlag           = "detach"
	isK3sFlag            = "is-k3s"
	netPidFlag           = "net-pid"
	tcpEstablishedFlag   = "tcp-established"
	tcpCloseFlag         = "tcp-close"
	gpuEnabledFlag       = "gpu-enabled"
	logRedirectFlag      = "log-redirect"
	startChrootFlag      = "start-chroot"
	setupHostFlag        = "setup-host"
	restartFlag          = "restart"
	pidFlag              = "pid"
	externalFlag         = "external"
	destFlag             = "dest"
	containerStorageFlag = "container-storage"
	configFlag           = "config"
	configDirFlag        = "config-dir"
	typeFlag             = "type"
	attachFlag           = "attach"
	streamFlag           = "stream"
	leaveRunningFlag     = "leave-running"
	fileLocksFlag        = "file-locks"
	vsockEnabledFlag     = "vsock"
	portFlag             = "port"
	metricsEnabledFlag   = "metrics-enabled"
	jobServiceFlag       = "job-service"
	noStdinFlag          = "no-stdin"
	pidFileFlag          = "pid-file"
	modeFlag             = "mode"
	vmSnapshotFlag       = "vm-snapshot"
	vmSocketPathFlag     = "vm-socket-path"
	skipInFlightFlag     = "skip-in-flight"
)
