name: GetRunner

permissions:
  contents: read
  packages: read
  id-token: write
  pull-requests: write
  checks: write

on:
  workflow_call:
    outputs:
      gpu_type:
        description: "The GPU type label for the dynamic runner."
        value: ${{ jobs.create-runner.outputs.gpu_type }}
      instance_id:
        description: "The instance ID of the created runner."
        value: ${{ jobs.create-runner.outputs.instance_id }}

jobs:
  create-runner:
    runs-on: ubuntu-latest
    outputs:
      runner_name: ${{ steps.create_runner.outputs.runner_name }}
      instance_id: ${{ steps.create_runner.outputs.instance_id }}
      gpu_type: ${{ steps.create_runner.outputs.gpu_type }}
    steps:
      - name: Create runner
        id: create_runner
        run: |
          set -euo pipefail
          GPU_TYPE="A100"

          # build JSON safely
          request=$(jq -n \
            --arg owner "${{ github.repository_owner }}" \
            --arg repo "${{ github.repository }}" \
            --arg gpu "$GPU_TYPE" \
            '{owner:$owner, repo:$repo, labels:["self-hosted",$gpu], num_gpus:1, gpu_type:$gpu}')
          echo "$request" > request.json

          response=$(curl --fail -s -X POST \
            -H "Content-Type: application/json" \
            -d @request.json \
            "${{ secrets.CEDANA_GA_RUNNER_URL }}/v1/runners/create")

          # parse response (adjust jq paths if your API uses different field names)
          instance_id=$(echo "$response" | jq -r '.instance_id // empty')
          runner_name=$(echo "$response" | jq -r '.runner_name // empty')
          gpu_type=$(echo "$response" | jq -r '.gpu_type // empty')

          echo "instance_id=$instance_id" >> "$GITHUB_OUTPUT"
          echo "runner_name=$runner_name" >> "$GITHUB_OUTPUT"
          echo "gpu_type=$gpu_type" >> "$GITHUB_OUTPUT"

  validate-runner:
    needs: create-runner
    runs-on: ["self-hosted", "${{ needs.create-runner.outputs.gpu_type }}"]
    timeout-minutes: 40
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a test
        run: |
          echo "Hello from the new runner!"
          ls -la
