name: Manual

on:
  workflow_dispatch:
    inputs:
      gpu_version:
        type: string
        description: Version for GPU binaries (branch name or "release" for latest release)
        required: false
        default: "release"
      streamer_version:
        type: string
        description: Version for streamer binaries (branch name or "release" for latest release)
        required: false
        default: "release"
      bench_cedana:
        type: boolean
        description: Run benchmarks for Cedana
        required: false
        default: false
      bench_native:
        type: boolean
        description: Run benchmarks for native
        required: false
        default: false
      bench_samples:
        type: number
        description: Number of samples to run for each metric
        required: false
        default: 2
      bench_push_results:
        type: boolean
        description: Push benchmark results to storage
        required: false
        default: false
      bench_comparison_patch:
        type: boolean
        description: Compare benchmark results with last patch
        required: false
        default: false
      bench_comparison_native:
        type: boolean
        description: Compare benchmark results with native
        required: false
        default: false
      bench_post_summary_slack:
        type: boolean
        description: Post benchmark summary to Slack
        required: false
        default: false
      bench_post_summary_slack_branded:
        type: boolean
        description: Post benchmark summary to Slack (ext channel) with branding
        required: false
        default: false
      bench_result_dataset:
        type: string
        description: "BigQuery dataset to push results to"
        required: false
        default: "cedana_alpha"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    if: inputs.bench_cedana
    with:
      amd64: true

  download:
    name: Download
    uses: ./.github/workflows/download.yml
    secrets: inherit
    if: inputs.bench_cedana
    with:
      gpu_version: ${{ inputs.gpu_version }}
      streamer_version: ${{ inputs.streamer_version }}

  bench:
    name: Bench
    uses: ./.github/workflows/bench.yml
    if: always() || github.event.inputs.bench_cedana || github.event.inputs.bench_native
    needs: [build, download]
    secrets: inherit
    with:
      cedana: ${{ inputs.bench_cedana }}
      native: ${{ inputs.bench_native }}
      samples: ${{ inputs.bench_samples }}
      push_results: ${{ inputs.bench_push_results }}
      comparison_patch: ${{ inputs.bench_comparison_patch }}
      comparison_native: ${{ inputs.bench_comparison_native }}
      post_summary_slack: ${{ inputs.bench_post_summary_slack }}
      post_summary_slack_branded: ${{ inputs.bench_post_summary_slack_branded }}
      result_dataset: ${{ inputs.bench_result_dataset }}
