name: Manual (bench)

on:
  workflow_dispatch:
    inputs:
      cedana_version:
        type: string
        description: Version for Cedana binaries (branch name or "release" for latest release)
        required: false
        default: "main"
      gpu_version:
        type: string
        description: Version for GPU binaries (branch name or "release" for latest release)
        required: false
        default: "main"
      streamer_version:
        type: string
        description: Version for streamer binaries (branch name or "release" for latest release)
        required: false
        default: "main"
      runtime:
        type: choice
        description: Runtime to run benchmark on
        required: true
        options:
          - native
          - cedana
      bench_samples:
        type: number
        description: Number of samples to run for each metric
        required: false
        default: 2
      bench_comparison_previous:
        type: boolean
        description: Compare benchmark results with previous
        required: false
        default: false
      bench_comparison_runtime:
        type: boolean
        description: Compare benchmark results with other runtimes
        required: false
        default: false
      bench_push_results:
        type: boolean
        description: "Push benchmark results to storage"
        required: false
        default: false
      bench_results_dataset:
        type: string
        description: "BigQuery dataset to push results to"
        required: false
        default: "cedana_alpha"
      runner:
        type: string
        description: "Runner machine for benchmarks"
        required: false
        default: "8cpu-32g-1xL4"

jobs:
  download:
    name: Download
    uses: ./.github/workflows/download.yml
    secrets: inherit
    if: inputs.runtime == 'cedana'
    with:
      cedana_version: ${{ inputs.cedana_version }}
      gpu_version: ${{ inputs.gpu_version }}
      streamer_version: ${{ inputs.streamer_version }}

  bench:
    name: Bench
    uses: ./.github/workflows/bench.yml
    if: ${{ !cancelled() }}
    needs: download
    secrets: inherit
    with:
      cedana: ${{ inputs.runtime == 'cedana' }}
      native: ${{ inputs.runtime == 'native' }}
      samples: ${{ inputs.bench_samples }}
      comparison_previous: ${{ inputs.bench_comparison_previous }}
      comparison_runtime: ${{ inputs.bench_comparison_runtime }}
      push_results: ${{ inputs.bench_push_results }}
      results_dataset: ${{ inputs.bench_results_dataset }}
      runner: ${{ inputs.runner }}
