name: PR (Cancel)

on:
  pull_request:
    types: [closed]

jobs:
  cancel-pr-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel running workflows for this PR
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
          ignore_sha: true
