name: PR (Cancel)

on:
  pull_request:
    types: [closed]

concurrency:
  group: ${{ github.repository }}-pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cancel:
    name: Cancel
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing (github concurrency should cancel the workflow)
        run: echo "This workflow is intended to cancel any in-progress workflows for the same PR."
