name: Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_test:
        type: boolean
        description: 'Run tests with debugging enabled'
        required: false
        default: false

concurrency:
  group: cedana-push-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    uses: ./.github/workflows/pr.yml
    with:
      debug_build: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_test }}
      debug_smoke_test: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_test }}
      debug_regression_test: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_test }}
