name: Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_build:
        type: boolean
        description: "Run build with debugging enabled"
        required: false
        default: false
      debug_test:
        type: boolean
        description: "Run tests with debugging enabled"
        required: false
        default: false
      debug_bench:
        type: boolean
        description: "Run benchmark with debugging enabled"
        required: false
        default: false
      debug_publish:
        type: boolean
        description: "Run publish with debugging enabled"
        required: false
        default: false

concurrency:
  group: ${{ github.repository }}-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_build }}
      cedana: true
      plugins: true
      image: true
      image_name: cedana/cedana-helper-test

  download:
    name: Download
    uses: ./.github/workflows/download.yml
    secrets: inherit
    with:
      criu_version: release
      gpu_version: main
      streamer_version: main
      helm_chart_version: main
      controller_version: staging
      runtime_shim_version: release

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    needs: [build, download]
    secrets: inherit
    with:
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_test }}

  bench:
    name: Bench
    uses: ./.github/workflows/bench.yml
    needs: [build, download]
    secrets: inherit
    with:
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_bench }}
      samples: 2
      push_results: true
      results_dataset: cedana_alpha
      post_summary_pr: false

  publish:
    name: Publish
    uses: ./.github/workflows/publish.yml
    needs: build
    secrets: inherit
    with:
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_publish }}
      cloudsmith: true
      cloudsmith_repo: cedana-alpha
      dockerhub: true
      post_summary: false
