name: Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_test:
        type: boolean
        description: 'Run tests with debugging enabled'
        required: false
        default: false

concurrency:
  group: cedana-push-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    uses: ./.github/workflows/pr.yml
    permissions:
      contents: 'read'
      packages: 'read'
      id-token: 'write'
      pull-requests: 'write'
    with:
      debug_build: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_test }}
      debug_smoke_test: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_test }}
      debug_regression_test: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_test }}
      debug_correctness_test: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_test }}
      debug_unit_test: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_test }}
      debug_bench: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_test }}
      skip_bench: true
      skip_shellcheck: true
