name: Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_build:
        type: boolean
        description: "Run build with debugging enabled"
        required: false
        default: false
      debug_test:
        type: boolean
        description: "Run tests with debugging enabled"
        required: false
        default: false
      debug_bench:
        type: boolean
        description: "Run benchmark with debugging enabled"
        required: false
        default: false

concurrency:
  group: cedana-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_build }}
      publish_alpha: true

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    needs: build
    secrets: inherit
    with:
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_test }}

  bench:
    name: Bench
    uses: ./.github/workflows/bench.yml
    needs: build
    secrets: inherit
    with:
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_bench }}
      samples: 3
      push_results: true
      post_summary_pr: false
      post_summary_slack: false
