name: Weekly
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
      inputs:
        debug_benchmark:
          type: boolean
          description: 'Run benchmark with debugging enabled'
          required: false
          default: false

# Cancel any preceding run on the pull request.
concurrency:
  group: cedana-weekly-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Benchmark
    permissions:
      contents: 'read'
      packages: 'read'
      id-token: 'write'

    runs-on: ubicloud-standard-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
          fetch-tags: true

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        env:
          WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_POOL }}
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: 'benchmark-uploader@cedana-benchmarking.iam.gserviceaccount.com'

      - name: Setup debugging session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_benchmark }}
        with:
          limit-access-to-actor: true

      - name: Setup CI
        run:  sudo -E make -C scripts/ci setup-full

      - name: Run Benchmarking Script (${{ matrix.os }})
        run: sudo -E make -C scripts/ci benchmark
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
          GOOGLE_CLOUD_PROJECT: ${{ steps.auth.outputs.project_id }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          CEDANA_URL: ${{ secrets.CHECKPOINTSVC_URL }}
          BENCHMARK_ACCOUNT: ${{ secrets.BENCHMARK_ACCOUNT }}
          BENCHMARK_ACCOUNT_PW: ${{ secrets.BENCHMARK_ACCOUNT_PW }}
          SIGNOZ_ACCESS_TOKEN: ${{ secrets.SIGNOZ_ACCESS_TOKEN }}

